/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;
import model.ModelCliente;

/**
 *
 * @author jefer
 */
public class Cliente extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelCliente = new ArrayList<>();
    String salvarAlterar; //Varilavel global que vai ser usada no if do botao salvar para determinar se é para alterar ou salvar um novo produto

    public Cliente() {
        initComponents();
        carregarCliente();
        setLocationRelativeTo(null);
        habilitaDesabilita(false);
        limparCampos();
        setAlwaysOnTop(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/carrinho-de-compras.png")));
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Maiandra GD",Font.PLAIN,35)));
        jTextFieldPesquisarCliente.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigoCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldEnderecoCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldBairroCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldCidadeCliente = new javax.swing.JTextField();
        jComboBoxUFCliente = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        jButtonNovoCliente = new javax.swing.JButton();
        jButtonAlterarCliente = new javax.swing.JButton();
        jButtonSalvarCliente = new javax.swing.JButton();
        jButtonCancelarCliente = new javax.swing.JButton();
        jTextFieldCEPCliente = new javax.swing.JFormattedTextField();
        jTextFieldTelefoneCliente = new javax.swing.JFormattedTextField();
        jButtonPesquisarCliente = new javax.swing.JButton();
        jTextFieldPesquisarCliente = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        jLabel3.setText("Nome");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Vendas - Cadastro e Busca de Clientes");

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel1.setText("Código:");

        jTextFieldCodigoCliente.setEditable(false);
        jTextFieldCodigoCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldCodigoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCodigoCliente.setEnabled(false);
        jTextFieldCodigoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoClienteActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel2.setText("Nome:");

        jTextFieldNomeCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldNomeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNomeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeClienteActionPerformed(evt);
            }
        });

        jTextFieldEnderecoCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldEnderecoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldEnderecoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoClienteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel4.setText("Endereço:");

        jTextFieldBairroCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldBairroCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldBairroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBairroClienteActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel5.setText("Bairro");

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel6.setText("Cidade:");

        jTextFieldCidadeCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldCidadeCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCidadeCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeClienteActionPerformed(evt);
            }
        });

        jComboBoxUFCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jComboBoxUFCliente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBoxUFCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UF");

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel8.setText("CEP:");

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel9.setText("Telefone:");

        jTableClientes.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cidade", "UF", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.setAutoscrolls(false);
        jTableClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableClientes.setRowHeight(30);
        jScrollPane1.setViewportView(jTableClientes);
        if (jTableClientes.getColumnModel().getColumnCount() > 0) {
            jTableClientes.getColumnModel().getColumn(0).setMinWidth(100);
            jTableClientes.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableClientes.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableClientes.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTableClientes.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTableClientes.getColumnModel().getColumn(3).setMinWidth(100);
            jTableClientes.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableClientes.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableClientes.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        jButtonNovoCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonNovoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/papel-de-texto.png"))); // NOI18N
        jButtonNovoCliente.setText("Novo");
        jButtonNovoCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNovoCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoCliente.setMaximumSize(new java.awt.Dimension(100, 40));
        jButtonNovoCliente.setMinimumSize(new java.awt.Dimension(100, 40));
        jButtonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoClienteActionPerformed(evt);
            }
        });

        jButtonAlterarCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/editar.png"))); // NOI18N
        jButtonAlterarCliente.setText("Alterar");
        jButtonAlterarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAlterarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlterarCliente.setMaximumSize(new java.awt.Dimension(100, 40));
        jButtonAlterarCliente.setMinimumSize(new java.awt.Dimension(100, 40));
        jButtonAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarClienteActionPerformed(evt);
            }
        });

        jButtonSalvarCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonSalvarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/disquete.png"))); // NOI18N
        jButtonSalvarCliente.setText("Salvar");
        jButtonSalvarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvarCliente.setMaximumSize(new java.awt.Dimension(100, 40));
        jButtonSalvarCliente.setMinimumSize(new java.awt.Dimension(100, 40));
        jButtonSalvarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarClienteActionPerformed(evt);
            }
        });

        jButtonCancelarCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonCancelarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/proibido.png"))); // NOI18N
        jButtonCancelarCliente.setText("Cancelar");
        jButtonCancelarCliente.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancelarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelarCliente.setMaximumSize(new java.awt.Dimension(100, 40));
        jButtonCancelarCliente.setMinimumSize(new java.awt.Dimension(100, 40));
        jButtonCancelarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarClienteActionPerformed(evt);
            }
        });

        try {
            jTextFieldCEPCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCEPCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldCEPCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCEPClienteActionPerformed(evt);
            }
        });

        try {
            jTextFieldTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldTelefoneCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldTelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneClienteActionPerformed(evt);
            }
        });

        jButtonPesquisarCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonPesquisarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/pesquisa.png"))); // NOI18N
        jButtonPesquisarCliente.setText("Pesquisar");
        jButtonPesquisarCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarClienteActionPerformed(evt);
            }
        });

        jTextFieldPesquisarCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldPesquisarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarClienteKeyPressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel13.setText("Pesquisar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldNomeCliente)))
                .addGap(12, 12, 12))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldBairroCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCidadeCliente)
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxUFCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCEPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPesquisarCliente)))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAlterarCliente, jButtonNovoCliente, jButtonSalvarCliente});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldCodigoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldBairroCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextFieldCidadeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxUFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldCEPCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jButtonPesquisarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(jButtonSalvarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                        .addComponent(jButtonAlterarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCancelarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonAlterarCliente, jButtonNovoCliente, jButtonSalvarCliente});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Habilita ou desabilita campos e botoes
    private void habilitaDesabilita(boolean condicao) {
        jTextFieldNomeCliente.setEnabled(condicao);
        jTextFieldEnderecoCliente.setEnabled(condicao);
        jTextFieldBairroCliente.setEnabled(condicao);
        jTextFieldCidadeCliente.setEnabled(condicao);
        jTextFieldCEPCliente.setEnabled(condicao);
        jTextFieldTelefoneCliente.setEnabled(condicao);
        jComboBoxUFCliente.setEnabled(condicao);
        jButtonSalvarCliente.setEnabled(condicao);
    }

    //Limpa os campos quando clicar em algum botão
    private void limparCampos() {
        jTextFieldCodigoCliente.setText("");
        jTextFieldNomeCliente.setText("");
        jTextFieldEnderecoCliente.setText("");
        jTextFieldBairroCliente.setText("");
        jTextFieldCidadeCliente.setText("");
        jTextFieldCEPCliente.setText("");
        jTextFieldTelefoneCliente.setText("");
    }

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextFieldTelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneClienteActionPerformed

    private void jTextFieldCEPClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCEPClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEPClienteActionPerformed

    private void jButtonCancelarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarClienteActionPerformed
        // TODO add your handling code here:
        this.habilitaDesabilita(false);
        this.limparCampos();
        jTextFieldPesquisarCliente.requestFocus();
    }//GEN-LAST:event_jButtonCancelarClienteActionPerformed

    private void jButtonSalvarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarClienteActionPerformed
        // TODO add your handling code here:
        try {
            modelCliente.setIdCliente(Integer.parseInt(this.jTextFieldCodigoCliente.getText()));
        } catch (NumberFormatException e) {

        }
        if (!jTextFieldNomeCliente.getText().isEmpty() && !jTextFieldEnderecoCliente.getText().isEmpty()
                && !jTextFieldBairroCliente.getText().isEmpty() && !jTextFieldCidadeCliente.getText().isEmpty()) {
            modelCliente.setCliNome(this.jTextFieldNomeCliente.getText().toUpperCase());
            modelCliente.setCliEndereco(this.jTextFieldEnderecoCliente.getText().toUpperCase());
            modelCliente.setCliBairro(this.jTextFieldBairroCliente.getText().toUpperCase());
            modelCliente.setCliCidade(this.jTextFieldCidadeCliente.getText().toUpperCase());
            modelCliente.setCliUf((String) this.jComboBoxUFCliente.getSelectedItem());
            modelCliente.setCliCep(this.jTextFieldCEPCliente.getText());
            modelCliente.setCliTelefone(this.jTextFieldTelefoneCliente.getText());
            if (salvarAlterar.equals("salvar")) {
                if (controllerCliente.salvarClienteController(modelCliente) > 0) {
                    JOptionPane.showMessageDialog(this, "Cliente Salvo com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    carregarCliente(); //aqui carrega os clientes na tabela
                    habilitaDesabilita(false);
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao Salvar o Cliente!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                if (controllerCliente.atualizarClienteController(modelCliente)) {
                    JOptionPane.showMessageDialog(this, "Cliente Alterado com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    carregarCliente(); //aqui carrega os clientes na tabela
                    habilitaDesabilita(false);
                    limparCampos();
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao Alterar o Cliente!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao "+salvarAlterar+" o Cliente!\nNome ou Algum campo de endereço VAZIO", "ERRO", JOptionPane.ERROR_MESSAGE);

        }
        jTextFieldPesquisarCliente.setEnabled(true);
        jButtonPesquisarCliente.setEnabled(true);
    }//GEN-LAST:event_jButtonSalvarClienteActionPerformed

    private void jButtonAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarClienteActionPerformed
        // TODO add your handling code here:
        int linha = jTableClientes.getSelectedRow(); /* pega o valor da linha selecionada*/

        salvarAlterar = "alterar";
        try {
            jTextFieldPesquisarCliente.setEnabled(false);
            jButtonPesquisarCliente.setEnabled(false);
            int codigoCliente = (int) jTableClientes.getValueAt(linha, 0); /* Pega o valor da coluna da linha selecionada*/

            this.habilitaDesabilita(true);

            // Recupera os dados do banco
            modelCliente = controllerCliente.getClienteController(codigoCliente);
            //Jogar na interface
            jTextFieldCodigoCliente.setText(String.valueOf(modelCliente.getIdCliente()));
            jTextFieldNomeCliente.setText(modelCliente.getCliNome());
            jTextFieldEnderecoCliente.setText(modelCliente.getCliEndereco());
            jTextFieldBairroCliente.setText(modelCliente.getCliBairro());
            jTextFieldCidadeCliente.setText(modelCliente.getCliCidade());
            jTextFieldCEPCliente.setText(modelCliente.getCliCep());
            jTextFieldTelefoneCliente.setText(modelCliente.getCliTelefone());
            jComboBoxUFCliente.setSelectedItem(modelCliente.getCliUf());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Alterar o Cliente, Selecione um Registro na tabela", "AVISO", JOptionPane.ERROR_MESSAGE);
            jTextFieldPesquisarCliente.setEnabled(true);
            jButtonPesquisarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonAlterarClienteActionPerformed

    private void jButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoClienteActionPerformed
        // TODO add your handling code here:
        salvarAlterar = "salvar";
        this.habilitaDesabilita(true);
        this.limparCampos();
        jTextFieldNomeCliente.requestFocus();
    }//GEN-LAST:event_jButtonNovoClienteActionPerformed

    private void jTextFieldCidadeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeClienteActionPerformed

    private void jTextFieldBairroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBairroClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBairroClienteActionPerformed

    private void jTextFieldEnderecoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoClienteActionPerformed

    private void jTextFieldNomeClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeClienteActionPerformed

    private void jTextFieldCodigoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoClienteActionPerformed

    private void jButtonPesquisarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarClienteActionPerformed
        // TODO add your handling code here:
        pesquisarCliente();
    }//GEN-LAST:event_jButtonPesquisarClienteActionPerformed

    private void jTextFieldPesquisarClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarClienteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            pesquisarCliente();
        }
    }//GEN-LAST:event_jTextFieldPesquisarClienteKeyPressed

    //Método para carregar os clientes na tabela
    private void carregarCliente() {
        listaModelCliente = controllerCliente.getListaClienteController();
        DefaultTableModel modelo = (DefaultTableModel) jTableClientes.getModel();
        modelo.setNumRows(0);
        int cont = listaModelCliente.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelCliente.get(i).getIdCliente(),
                listaModelCliente.get(i).getCliNome(),
                listaModelCliente.get(i).getCliCidade(),
                listaModelCliente.get(i).getCliUf(),
                listaModelCliente.get(i).getCliTelefone(),
                listaModelCliente.get(i).getCliEndereco(),
                listaModelCliente.get(i).getCliBairro(),
                listaModelCliente.get(i).getCliCep(),});
        }
        JTableHeader cabecalho = jTableClientes.getTableHeader();
        cabecalho.setFont(new Font("Maiandra GD", Font.PLAIN, 24));
    }

    private void pesquisarCliente() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTableClientes.getModel();
        final TableRowSorter<DefaultTableModel> classificador = new TableRowSorter<>(modelo);
        this.jTableClientes.setRowSorter(classificador);
        String texto = jTextFieldPesquisarCliente.getText().toUpperCase();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarCliente;
    private javax.swing.JButton jButtonCancelarCliente;
    private javax.swing.JButton jButtonNovoCliente;
    private javax.swing.JButton jButtonPesquisarCliente;
    private javax.swing.JButton jButtonSalvarCliente;
    private javax.swing.JComboBox jComboBoxUFCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableClientes;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldBairroCliente;
    private javax.swing.JFormattedTextField jTextFieldCEPCliente;
    private javax.swing.JTextField jTextFieldCidadeCliente;
    private javax.swing.JTextField jTextFieldCodigoCliente;
    private javax.swing.JTextField jTextFieldEnderecoCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPesquisarCliente;
    private javax.swing.JFormattedTextField jTextFieldTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
