/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerFornecedor;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;
import model.ModelFornecedor;

/**
 *
 * @author jefer
 */
public class Fornecedores extends javax.swing.JFrame {

    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ModelFornecedor modelFornecedor = new ModelFornecedor();
    ArrayList<ModelFornecedor> listaModelFornecedores = new ArrayList<>();
    String salvarAlterar; //Varilavel global que vai ser usada no if do botao salvar para determinar se é para alterar ou salvar um novo produto

    public Fornecedores() {
        initComponents();
        setAlwaysOnTop(true);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        habilitaDesabilita(false);
        carregarFornecedores();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/carrinho-de-compras.png")));
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Maiandra GD", Font.PLAIN, 35)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigoFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRazaoSocial = new javax.swing.JTextField();
        jTextFieldEnderecoFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxUFFornecedor = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFornecedores = new javax.swing.JTable();
        jButtonNovoFornecedor = new javax.swing.JButton();
        jButtonAlterarFornecedor = new javax.swing.JButton();
        jButtonSalvarFornecedor = new javax.swing.JButton();
        jButtonCancelarFornecedor = new javax.swing.JButton();
        jTextFieldCEPFornecedor = new javax.swing.JFormattedTextField();
        jTextFieldTelefoneFornecedor = new javax.swing.JFormattedTextField();
        jButtonPesquisarFornecedor = new javax.swing.JButton();
        jTextFieldPesquisarFornecedor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNomeFantasia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldCNPJ = new javax.swing.JFormattedTextField();
        jTextFieldInscricaoEstadual = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldBairroFornecedor = new javax.swing.JTextField();
        jTextFieldCidadeFornecedor = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEMailFornecedor = new javax.swing.JTextField();

        jLabel3.setText("Nome");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Vendas - Cadastro e Busca de Fornecedores");

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel1.setText("Código:");

        jTextFieldCodigoFornecedor.setEditable(false);
        jTextFieldCodigoFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldCodigoFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldCodigoFornecedor.setEnabled(false);
        jTextFieldCodigoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoFornecedorActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel2.setText("Nome Fantasia:");

        jTextFieldRazaoSocial.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldRazaoSocial.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldRazaoSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRazaoSocialActionPerformed(evt);
            }
        });

        jTextFieldEnderecoFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldEnderecoFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldEnderecoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEnderecoFornecedorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel4.setText("Endereço:");

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel5.setText("Bairro:");

        jComboBoxUFFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jComboBoxUFFornecedor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        jComboBoxUFFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("UF");

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel8.setText("CEP:");

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel9.setText("Telefone:");

        jTableFornecedores.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTableFornecedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Cidade", "UF", "Telefone", "E-Mail", "CNPJ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFornecedores.setAutoscrolls(false);
        jTableFornecedores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableFornecedores.setRowHeight(30);
        jScrollPane1.setViewportView(jTableFornecedores);
        if (jTableFornecedores.getColumnModel().getColumnCount() > 0) {
            jTableFornecedores.getColumnModel().getColumn(0).setMinWidth(100);
            jTableFornecedores.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableFornecedores.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableFornecedores.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTableFornecedores.getColumnModel().getColumn(2).setMinWidth(200);
            jTableFornecedores.getColumnModel().getColumn(2).setPreferredWidth(200);
            jTableFornecedores.getColumnModel().getColumn(2).setMaxWidth(200);
            jTableFornecedores.getColumnModel().getColumn(3).setMinWidth(70);
            jTableFornecedores.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTableFornecedores.getColumnModel().getColumn(3).setMaxWidth(70);
            jTableFornecedores.getColumnModel().getColumn(4).setMinWidth(200);
            jTableFornecedores.getColumnModel().getColumn(4).setPreferredWidth(200);
            jTableFornecedores.getColumnModel().getColumn(4).setMaxWidth(200);
            jTableFornecedores.getColumnModel().getColumn(5).setMinWidth(400);
            jTableFornecedores.getColumnModel().getColumn(5).setPreferredWidth(400);
            jTableFornecedores.getColumnModel().getColumn(5).setMaxWidth(400);
            jTableFornecedores.getColumnModel().getColumn(6).setMinWidth(230);
            jTableFornecedores.getColumnModel().getColumn(6).setPreferredWidth(230);
            jTableFornecedores.getColumnModel().getColumn(6).setMaxWidth(230);
        }

        jButtonNovoFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonNovoFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/papel-de-texto.png"))); // NOI18N
        jButtonNovoFornecedor.setText("Novo");
        jButtonNovoFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNovoFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoFornecedor.setMaximumSize(new java.awt.Dimension(100, 40));
        jButtonNovoFornecedor.setMinimumSize(new java.awt.Dimension(100, 40));
        jButtonNovoFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoFornecedorActionPerformed(evt);
            }
        });

        jButtonAlterarFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonAlterarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/editar.png"))); // NOI18N
        jButtonAlterarFornecedor.setText("Alterar");
        jButtonAlterarFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAlterarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlterarFornecedor.setMaximumSize(new java.awt.Dimension(100, 40));
        jButtonAlterarFornecedor.setMinimumSize(new java.awt.Dimension(100, 40));
        jButtonAlterarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarFornecedorActionPerformed(evt);
            }
        });

        jButtonSalvarFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonSalvarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/disquete.png"))); // NOI18N
        jButtonSalvarFornecedor.setText("Salvar");
        jButtonSalvarFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvarFornecedor.setMaximumSize(new java.awt.Dimension(100, 40));
        jButtonSalvarFornecedor.setMinimumSize(new java.awt.Dimension(100, 40));
        jButtonSalvarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarFornecedorActionPerformed(evt);
            }
        });

        jButtonCancelarFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonCancelarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/proibido.png"))); // NOI18N
        jButtonCancelarFornecedor.setText("Cancelar");
        jButtonCancelarFornecedor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancelarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelarFornecedor.setMaximumSize(new java.awt.Dimension(100, 40));
        jButtonCancelarFornecedor.setMinimumSize(new java.awt.Dimension(100, 40));
        jButtonCancelarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarFornecedorActionPerformed(evt);
            }
        });

        try {
            jTextFieldCEPFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCEPFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldCEPFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCEPFornecedorActionPerformed(evt);
            }
        });

        try {
            jTextFieldTelefoneFornecedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldTelefoneFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldTelefoneFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneFornecedorActionPerformed(evt);
            }
        });

        jButtonPesquisarFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonPesquisarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/pesquisa.png"))); // NOI18N
        jButtonPesquisarFornecedor.setText("Pesquisar");
        jButtonPesquisarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarFornecedorActionPerformed(evt);
            }
        });

        jTextFieldPesquisarFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldPesquisarFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarFornecedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisarFornecedorKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel13.setText("Pesquisar:");

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel10.setText("Razão Social:");

        jTextFieldNomeFantasia.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldNomeFantasia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldNomeFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFantasiaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel11.setText("CNPJ:");

        try {
            jTextFieldCNPJ.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/0001-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldCNPJ.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCNPJActionPerformed(evt);
            }
        });

        try {
            jTextFieldInscricaoEstadual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.####-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldInscricaoEstadual.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldInscricaoEstadual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInscricaoEstadualActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel12.setText("Inscrição Estadual:");

        jTextFieldBairroFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N

        jTextFieldCidadeFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldCidadeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCidadeFornecedorActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel14.setText("Cidade:");

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel6.setText("E-Mail:");

        jTextFieldEMailFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCEPFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldEMailFornecedor))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jButtonNovoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 588, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jComboBoxUFFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldPesquisarFornecedor)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonPesquisarFornecedor))
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNomeFantasia))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldRazaoSocial)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldBairroFornecedor))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldEnderecoFornecedor)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldCidadeFornecedor)))))))
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEnderecoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel4))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldInscricaoEstadual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCidadeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTextFieldBairroFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel14)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldCEPFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldTelefoneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(jTextFieldEMailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jTextFieldPesquisarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonPesquisarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxUFFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNovoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonSalvarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancelarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void habilitaDesabilita(boolean condicao) {
        jTextFieldRazaoSocial.setEnabled(condicao);
        jTextFieldNomeFantasia.setEnabled(condicao);
        jTextFieldCNPJ.setEnabled(condicao);
        jTextFieldInscricaoEstadual.setEnabled(condicao);
        jTextFieldEnderecoFornecedor.setEnabled(condicao);
        jTextFieldBairroFornecedor.setEnabled(condicao);
        jTextFieldCidadeFornecedor.setEnabled(condicao);
        jTextFieldCEPFornecedor.setEnabled(condicao);
        jTextFieldTelefoneFornecedor.setEnabled(condicao);
        jTextFieldEMailFornecedor.setEnabled(condicao);
        jComboBoxUFFornecedor.setEnabled(condicao);
        jButtonSalvarFornecedor.setEnabled(condicao);
    }

    private void limparCampos() {
        jTextFieldRazaoSocial.setText("");
        jTextFieldNomeFantasia.setText("");
        jTextFieldCNPJ.setText("");
        jTextFieldInscricaoEstadual.setText("");
        jTextFieldEnderecoFornecedor.setText("");
        jTextFieldBairroFornecedor.setText("");
        jTextFieldCidadeFornecedor.setText("");
        jTextFieldCEPFornecedor.setText("");
        jTextFieldTelefoneFornecedor.setText("");
        jTextFieldEMailFornecedor.setText("");
    }

    private void carregarFornecedores() {
        listaModelFornecedores = controllerFornecedor.getListaFornecedorController();
        DefaultTableModel modelo = (DefaultTableModel) jTableFornecedores.getModel();
        modelo.setNumRows(0);
        for (int i = 0; i < listaModelFornecedores.size(); i++) {
            modelo.addRow(new Object[]{
                listaModelFornecedores.get(i).getId_fornecedor(),
                listaModelFornecedores.get(i).getNome_fantasia(),
                listaModelFornecedores.get(i).getFor_cidade(),
                listaModelFornecedores.get(i).getFor_uf(),
                listaModelFornecedores.get(i).getFor_telefone(),
                listaModelFornecedores.get(i).getFor_email(),
                listaModelFornecedores.get(i).getCnpj()
            });
        }
        JTableHeader cabecalho = jTableFornecedores.getTableHeader();
        cabecalho.setFont(new Font("Maiandra GD", Font.PLAIN, 24));
    }

    private void pesquisarFornecedor() {
        DefaultTableModel modelo = (DefaultTableModel) this.jTableFornecedores.getModel();
        final TableRowSorter<DefaultTableModel> classificador = new TableRowSorter<>(modelo);
        this.jTableFornecedores.setRowSorter(classificador);
        String texto = jTextFieldPesquisarFornecedor.getText().toUpperCase();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextFieldTelefoneFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneFornecedorActionPerformed

    private void jTextFieldCEPFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCEPFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCEPFornecedorActionPerformed

    private void jButtonCancelarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarFornecedorActionPerformed
        // TODO add your handling code here:
        this.habilitaDesabilita(false);
        limparCampos();
        jTextFieldPesquisarFornecedor.setEnabled(true);
        jButtonPesquisarFornecedor.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarFornecedorActionPerformed

    private void jButtonSalvarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarFornecedorActionPerformed
        // TODO add your handling code here:
        try {
            modelFornecedor.setId_fornecedor(Integer.parseInt(jTextFieldCodigoFornecedor.getText()));
        } catch (Exception e) {
        }
        //INICIO - if else para mostrar a mensagem se algum campo for vazio
        if (!jTextFieldRazaoSocial.getText().isEmpty() && !jTextFieldNomeFantasia.getText().isEmpty()
                && !jTextFieldEnderecoFornecedor.getText().isEmpty() && !jTextFieldBairroFornecedor.getText().isEmpty()
                && !jTextFieldCidadeFornecedor.getText().isEmpty() && !jTextFieldCEPFornecedor.getText().isEmpty()
                && !jTextFieldTelefoneFornecedor.getText().isEmpty() && !jTextFieldEMailFornecedor.getText().isEmpty()
                && !jTextFieldCNPJ.getText().isEmpty() && !jTextFieldInscricaoEstadual.getText().isEmpty()) {
            modelFornecedor.setNome_fantasia(jTextFieldNomeFantasia.getText().toUpperCase());
            modelFornecedor.setRazao_social(jTextFieldRazaoSocial.getText().toUpperCase());
            modelFornecedor.setFor_endereco(jTextFieldEnderecoFornecedor.getText().toUpperCase());
            modelFornecedor.setFor_bairro(jTextFieldBairroFornecedor.getText().toUpperCase());
            modelFornecedor.setFor_cidade(jTextFieldCidadeFornecedor.getText().toUpperCase());
            modelFornecedor.setFor_cep(jTextFieldCEPFornecedor.getText().toUpperCase());
            modelFornecedor.setFor_uf(jComboBoxUFFornecedor.getSelectedItem().toString());
            modelFornecedor.setCnpj(jTextFieldCNPJ.getText());
            modelFornecedor.setInscricao_estadual(jTextFieldInscricaoEstadual.getText().toUpperCase());
            modelFornecedor.setFor_telefone(jTextFieldTelefoneFornecedor.getText());
            modelFornecedor.setFor_email(jTextFieldEMailFornecedor.getText());
            if (salvarAlterar.equals("SALVAR")) {// If para entrar na função de Salvar
                if (controllerFornecedor.salvarFornecedorController(modelFornecedor) > 0) {
                    JOptionPane.showMessageDialog(this, "Fornecedor Salvo com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    habilitaDesabilita(false);
                    limparCampos();
                    carregarFornecedores();
                    jTextFieldPesquisarFornecedor.setEnabled(true);
                    jButtonPesquisarFornecedor.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao " + salvarAlterar + " o Fornecedor!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else { // else para entrar na função de Alterar
                if (controllerFornecedor.atualizarFornecedorController(modelFornecedor)) {
                    JOptionPane.showMessageDialog(this, "Fornecedor Alterado com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    habilitaDesabilita(false);
                    limparCampos();
                    carregarFornecedores();
                    jTextFieldPesquisarFornecedor.setEnabled(true);
                    jButtonPesquisarFornecedor.setEnabled(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao " + salvarAlterar + " o Fornecedor!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {//FIM - if else para mostrar a mensagem se algum campo for vazio
            JOptionPane.showMessageDialog(this, "Erro ao " + salvarAlterar + " o Fornecedor!\nPreencha todos os campos", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonSalvarFornecedorActionPerformed

    private void jButtonAlterarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarFornecedorActionPerformed
        // TODO add your handling code here:
        try {
            salvarAlterar = "ALTERAR";
            int linha = jTableFornecedores.getSelectedRow();
            jTextFieldPesquisarFornecedor.setEnabled(false);
            jButtonPesquisarFornecedor.setEnabled(false);
            int codigoFornecedor = (int) jTableFornecedores.getValueAt(linha, 0);
            habilitaDesabilita(true);
            modelFornecedor = controllerFornecedor.getFornecedorController(codigoFornecedor);//pego os dados do fornecedor passando o codigo do fornecedor
            jTextFieldCodigoFornecedor.setText(String.valueOf(modelFornecedor.getId_fornecedor()));
            jTextFieldNomeFantasia.setText(modelFornecedor.getNome_fantasia());
            jTextFieldRazaoSocial.setText(modelFornecedor.getRazao_social());
            jTextFieldCNPJ.setText(modelFornecedor.getCnpj());
            jTextFieldEnderecoFornecedor.setText(modelFornecedor.getFor_endereco());
            jTextFieldInscricaoEstadual.setText(modelFornecedor.getInscricao_estadual());
            jTextFieldBairroFornecedor.setText(modelFornecedor.getFor_bairro());
            jTextFieldCidadeFornecedor.setText(modelFornecedor.getFor_cidade());
            jComboBoxUFFornecedor.setSelectedItem(modelFornecedor.getFor_uf());
            jTextFieldCEPFornecedor.setText(modelFornecedor.getFor_cep());
            jTextFieldTelefoneFornecedor.setText(modelFornecedor.getFor_telefone());
            jTextFieldEMailFornecedor.setText(modelFornecedor.getFor_email());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Alterar o Fornecedor, Selecione um Registro na tabela", "AVISO", JOptionPane.ERROR_MESSAGE);
            jTextFieldPesquisarFornecedor.setEnabled(true);
            jButtonPesquisarFornecedor.setEnabled(true);
        }

    }//GEN-LAST:event_jButtonAlterarFornecedorActionPerformed

    private void jButtonNovoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoFornecedorActionPerformed
        // TODO add your handling code here:
        salvarAlterar = "SALVAR";
        this.habilitaDesabilita(true);
        this.limparCampos();
        jTextFieldNomeFantasia.requestFocus();
        jTextFieldPesquisarFornecedor.setEnabled(false);
        jButtonPesquisarFornecedor.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoFornecedorActionPerformed

    private void jTextFieldEnderecoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEnderecoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEnderecoFornecedorActionPerformed

    private void jTextFieldRazaoSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRazaoSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldRazaoSocialActionPerformed

    private void jTextFieldCodigoFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoFornecedorActionPerformed

    private void jButtonPesquisarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarFornecedorActionPerformed
        // TODO add your handling code here:
        pesquisarFornecedor();
    }//GEN-LAST:event_jButtonPesquisarFornecedorActionPerformed

    private void jTextFieldPesquisarFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarFornecedorKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            pesquisarFornecedor();
        }
    }//GEN-LAST:event_jTextFieldPesquisarFornecedorKeyPressed

    private void jTextFieldPesquisarFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisarFornecedorKeyReleased
        // TODO add your handling code here:
        pesquisarFornecedor();
    }//GEN-LAST:event_jTextFieldPesquisarFornecedorKeyReleased

    private void jTextFieldNomeFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFantasiaActionPerformed

    private void jTextFieldCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCNPJActionPerformed

    private void jTextFieldInscricaoEstadualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInscricaoEstadualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInscricaoEstadualActionPerformed

    private void jTextFieldCidadeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCidadeFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCidadeFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fornecedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fornecedores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarFornecedor;
    private javax.swing.JButton jButtonCancelarFornecedor;
    private javax.swing.JButton jButtonNovoFornecedor;
    private javax.swing.JButton jButtonPesquisarFornecedor;
    private javax.swing.JButton jButtonSalvarFornecedor;
    private javax.swing.JComboBox jComboBoxUFFornecedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFornecedores;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldBairroFornecedor;
    private javax.swing.JFormattedTextField jTextFieldCEPFornecedor;
    private javax.swing.JFormattedTextField jTextFieldCNPJ;
    private javax.swing.JTextField jTextFieldCidadeFornecedor;
    private javax.swing.JTextField jTextFieldCodigoFornecedor;
    private javax.swing.JTextField jTextFieldEMailFornecedor;
    private javax.swing.JTextField jTextFieldEnderecoFornecedor;
    private javax.swing.JFormattedTextField jTextFieldInscricaoEstadual;
    private javax.swing.JTextField jTextFieldNomeFantasia;
    private javax.swing.JTextField jTextFieldPesquisarFornecedor;
    private javax.swing.JTextField jTextFieldRazaoSocial;
    private javax.swing.JFormattedTextField jTextFieldTelefoneFornecedor;
    // End of variables declaration//GEN-END:variables
}
