/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasProdutos;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.ModelProdutos;
import model.ModelSessaoUsuario;
import model.ModelVendas;
import model.ModelVendasProdutos;
import util.BLDatas;
import util.BLMascaras;

/**
 *
 * @author jefer
 */
public final class PDV extends javax.swing.JFrame {

    BLDatas bLDatas = new BLDatas();
    BLMascaras bLMascaras = new BLMascaras();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ControllerVendas controllerVendas = new ControllerVendas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    ModelVendas modelVendas = new ModelVendas();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ModelSessaoUsuario modelSessaoUsuario = new ModelSessaoUsuario();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutoses = new ArrayList<>();
    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();
    private final PagamentoPDV viewPagamentoPDV;
    int qtd;
    Double totalLiquidoVendaPDV, totalBrutoVendaPDV;

    /**
     * Creates new form PDV
     */
    public PDV() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        setarOperador();
        jTextFieldDescontoVendaPDV.setText("0");
        jTextFieldCodigoProdutoPDV.requestFocus();//inicia com o foco no jTextFieldCodigoProdutoPDV
        qtd = 1;
        this.viewPagamentoPDV = new PagamentoPDV(this, true);
        jLabelStatus.setText("ABERTO");
        mudarFonteTabela();
        carregarIcone();
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Maiandra GD", Font.PLAIN, 35)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaProdutosPDV = new javax.swing.JTable();
        jTextFieldCodigoProdutoPDV = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        uJPanelImagem6 = new componentes.UJPanelImagem();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelOperador = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jFormattedTextFieldValorBrutoVendaPDV = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextFieldValorLiquidoVendaPDV = new javax.swing.JFormattedTextField();
        jTextFieldDescontoVendaPDV = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSairPDV = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuComandosPDV = new javax.swing.JMenu();
        jMenuItemIncluirProduto = new javax.swing.JMenuItem();
        jMenuItemExcluirProduto = new javax.swing.JMenuItem();
        jMenuItemAlterarQuantidadePDV = new javax.swing.JMenuItem();
        jMenuItemFinalizarVendaPDV = new javax.swing.JMenuItem();
        jMenuItemPesquisarProdutosPDV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Vendas - Vendas PDV");
        setLocationByPlatform(true);
        setMaximumSize(null);
        setMinimumSize(null);
        setPreferredSize(null);
        setSize(new java.awt.Dimension(0, 0));

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));

        jTableListaProdutosPDV.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTableListaProdutosPDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Codigo", "Nome", "Quantidade", "Valor Unit.", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaProdutosPDV.setRowHeight(30);
        jTableListaProdutosPDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaProdutosPDVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaProdutosPDV);
        if (jTableListaProdutosPDV.getColumnModel().getColumnCount() > 0) {
            jTableListaProdutosPDV.getColumnModel().getColumn(0).setMinWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(0).setPreferredWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(0).setMaxWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(1).setMinWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(1).setMaxWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(3).setMinWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(3).setMaxWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(4).setMinWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(4).setMaxWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(5).setMinWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTableListaProdutosPDV.getColumnModel().getColumn(5).setMaxWidth(150);
        }

        jTextFieldCodigoProdutoPDV.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldCodigoProdutoPDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoProdutoPDVKeyReleased(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(204, 255, 153));

        uJPanelImagem6.setImagem(new java.io.File("C:\\Program Files (x86)\\JefersonTomas\\Sistema de Vendas com Controle de Estoque\\src\\imagens\\logo_pdv.png"));

        javax.swing.GroupLayout uJPanelImagem6Layout = new javax.swing.GroupLayout(uJPanelImagem6);
        uJPanelImagem6.setLayout(uJPanelImagem6Layout);
        uJPanelImagem6Layout.setHorizontalGroup(
            uJPanelImagem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );
        uJPanelImagem6Layout.setVerticalGroup(
            uJPanelImagem6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(uJPanelImagem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(uJPanelImagem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));

        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel4.setText("OPERADOR: ");

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel3.setText("STATUS: ");

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel2.setText("CAIXA: ");

        jLabelStatus.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabelStatus.setText("STATUS");

        jLabelOperador.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabelOperador.setText("OPERADOR");

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel7.setText("01");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelOperador))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelOperador))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelStatus))
                .addGap(24, 24, 24))
        );

        jLabel14.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("DESCONTO (em %)");

        jLabel15.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("VALOR TOTAL");

        jFormattedTextFieldValorBrutoVendaPDV.setEditable(false);
        jFormattedTextFieldValorBrutoVendaPDV.setFont(new java.awt.Font("Maiandra GD", 0, 20)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("TOTAL A PAGAR");

        jFormattedTextFieldValorLiquidoVendaPDV.setEditable(false);
        jFormattedTextFieldValorLiquidoVendaPDV.setFont(new java.awt.Font("Maiandra GD", 0, 20)); // NOI18N

        jTextFieldDescontoVendaPDV.setEditable(false);
        jTextFieldDescontoVendaPDV.setFont(new java.awt.Font("Maiandra GD", 0, 20)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Maiandra GD", 1, 20)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("COMANDOS");

        jLabel17.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("F2 - EXCLUIR PRODUTO");

        jLabel19.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("F3 - ALTERAR QUANTIDADE");

        jLabel20.setFont(new java.awt.Font("Maiandra GD", 1, 15)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("F4 - FINALIZAR VENDA");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldValorBrutoVendaPDV)
                    .addComponent(jFormattedTextFieldValorLiquidoVendaPDV)
                    .addComponent(jTextFieldDescontoVendaPDV)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDescontoVendaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addGap(20, 20, 20)
                .addComponent(jFormattedTextFieldValorBrutoVendaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jFormattedTextFieldValorLiquidoVendaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodigoProdutoPDV, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1234, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCodigoProdutoPDV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        jScrollPane2.setViewportView(jPanel2);

        jMenuBar1.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N

        jMenuSairPDV.setText("Arquivos");
        jMenuSairPDV.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem1.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/saida.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSairPDV.add(jMenuItem1);

        jMenuBar1.add(jMenuSairPDV);

        jMenuComandosPDV.setText("Comandos");
        jMenuComandosPDV.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N

        jMenuItemIncluirProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemIncluirProduto.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jMenuItemIncluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/carrinho-de-compras.png"))); // NOI18N
        jMenuItemIncluirProduto.setText("Incluir Produto");
        jMenuItemIncluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIncluirProdutoActionPerformed(evt);
            }
        });
        jMenuComandosPDV.add(jMenuItemIncluirProduto);

        jMenuItemExcluirProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemExcluirProduto.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jMenuItemExcluirProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/carrinho-de-compras-remover.png"))); // NOI18N
        jMenuItemExcluirProduto.setText("Excluir Produto");
        jMenuItemExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirProdutoActionPerformed(evt);
            }
        });
        jMenuComandosPDV.add(jMenuItemExcluirProduto);

        jMenuItemAlterarQuantidadePDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemAlterarQuantidadePDV.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jMenuItemAlterarQuantidadePDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/seta.png"))); // NOI18N
        jMenuItemAlterarQuantidadePDV.setText("Alterar Quantidade");
        jMenuItemAlterarQuantidadePDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarQuantidadePDVActionPerformed(evt);
            }
        });
        jMenuComandosPDV.add(jMenuItemAlterarQuantidadePDV);

        jMenuItemFinalizarVendaPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemFinalizarVendaPDV.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jMenuItemFinalizarVendaPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/final.png"))); // NOI18N
        jMenuItemFinalizarVendaPDV.setText("Finalizar Venda");
        jMenuItemFinalizarVendaPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinalizarVendaPDVActionPerformed(evt);
            }
        });
        jMenuComandosPDV.add(jMenuItemFinalizarVendaPDV);

        jMenuItemPesquisarProdutosPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemPesquisarProdutosPDV.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        jMenuItemPesquisarProdutosPDV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/pesquisa.png"))); // NOI18N
        jMenuItemPesquisarProdutosPDV.setText("Pesquisar Produtos");
        jMenuItemPesquisarProdutosPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPesquisarProdutosPDVActionPerformed(evt);
            }
        });
        jMenuComandosPDV.add(jMenuItemPesquisarProdutosPDV);

        jMenuBar1.add(jMenuComandosPDV);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        setSize(new java.awt.Dimension(1587, 865));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jMenuItemFinalizarVendaPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinalizarVendaPDVActionPerformed
        // TODO add your handling code here:
        int cont = jTableListaProdutosPDV.getRowCount();
        if (cont > 0) {
            viewPagamentoPDV.setValorTotal(Float.parseFloat(totalBrutoVendaPDV.toString()));
            viewPagamentoPDV.preencherCampos();
            viewPagamentoPDV.setVisible(true);

            jTextFieldDescontoVendaPDV.setText(String.valueOf(viewPagamentoPDV.getDesconto()));//pega o valor do desconto na view PagamentoPDV
            totalLiquidoVendaPDV = bLMascaras.arredondamentoComPontoDuasCasasDouble(Double.parseDouble(String.valueOf(viewPagamentoPDV.getTotalPagar())));//pega o valor do total a pagar na view PagamentoPDV e seta na totalLiquidoVendaPDV

            if (viewPagamentoPDV.isPago()) {
                salvarVendas();
                jLabelStatus.setText("ABERTO");
                limparVendas();
                qtd = 1;
            } else {
                jTextFieldDescontoVendaPDV.setText(String.valueOf(viewPagamentoPDV.getDesconto()));//pega o valor do desconto na view PagamentoPDV
                DecimalFormat df = new DecimalFormat("#,###.00");//formata as casas decimais de um Double
                jFormattedTextFieldValorBrutoVendaPDV.setText("R$: " + String.valueOf(df.format(totalBrutoVendaPDV)));//pega o valor do total na variavel global
                jFormattedTextFieldValorLiquidoVendaPDV.setText("R$: " + String.valueOf(df.format(totalLiquidoVendaPDV)));//pega o valor do total A PAGAR na variavel global
                JOptionPane.showMessageDialog(this, "Você nao concluiu o Pagamento", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Nenhum Produto na Tabela", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItemFinalizarVendaPDVActionPerformed

    private void jMenuItemAlterarQuantidadePDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarQuantidadePDVActionPerformed
        // TODO add your handling code here:
        qtd = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade desejada: "));
        System.err.println("Pressionando F3: " + qtd);
    }//GEN-LAST:event_jMenuItemAlterarQuantidadePDVActionPerformed

    private void jMenuItemExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirProdutoActionPerformed
        // TODO add your handling code here:
        int qtdLinha = jTableListaProdutosPDV.getRowCount();
        System.out.println(qtdLinha);
        if (qtdLinha < 1) {
            JOptionPane.showMessageDialog(this, "Erro ao Excluir a Venda, Nenhum Item na Tabela", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) jTableListaProdutosPDV.getModel();
            int linha = Integer.parseInt(JOptionPane.showInputDialog("Informe o ITEM que deseja excluir: "));
            modelo.removeRow(linha - 1);
            somaValorTotal();
            for (int i = 0; i < qtdLinha; i++) {
                modelo.setValueAt(i + 1, i, 0);
            }
        }
    }//GEN-LAST:event_jMenuItemExcluirProdutoActionPerformed

    private void jMenuItemIncluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncluirProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemIncluirProdutoActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTextFieldCodigoProdutoPDVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProdutoPDVKeyReleased
        // TODO add your handling code here:
        pegarCodigoF1(evt);
    }//GEN-LAST:event_jTextFieldCodigoProdutoPDVKeyReleased

    private void jTableListaProdutosPDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaProdutosPDVMouseClicked
        // TODO add your handling code here:
        mudarQuantidadeProduto();
    }//GEN-LAST:event_jTableListaProdutosPDVMouseClicked

    private void jMenuItemPesquisarProdutosPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPesquisarProdutosPDVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemPesquisarProdutosPDVActionPerformed

    public void carregarIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/carrinho_de_compras.png")));
    }

    private void mudarFonteTabela() {// muda a fonte da tabela de vendas
        JTableHeader cabecalho = jTableListaProdutosPDV.getTableHeader();
        cabecalho.setFont(new Font("Maiandra GD", Font.PLAIN, 24));
    }

    private void somaValorTotal() {
        double soma = 0, valor, liquido, desconto;
        int cont = jTableListaProdutosPDV.getRowCount();

        for (int i = 0; i < cont; i++) {
            valor = (double) jTableListaProdutosPDV.getValueAt(i, 5);
            soma += valor;
        }
        totalBrutoVendaPDV = bLMascaras.arredondamentoComPontoDuasCasasDouble(soma);
        desconto = Integer.parseInt(jTextFieldDescontoVendaPDV.getText());
        System.err.println("Valor do Desconto :" + desconto);
        liquido = soma - ((desconto / 100) * soma);
        System.err.println("Valor do Liquido :" + liquido);
        DecimalFormat df = new DecimalFormat("#,###.00");//formata as casas decimais de um Double
        jFormattedTextFieldValorBrutoVendaPDV.setText("R$: " + String.valueOf(df.format(soma)));
        jFormattedTextFieldValorLiquidoVendaPDV.setText("R$: " + String.valueOf(df.format(liquido)));
    }

    private void pegarCodigoF1(java.awt.event.KeyEvent e) {
        jLabelStatus.setText("OCUPADO");
        DefaultTableModel modelo = (DefaultTableModel) jTableListaProdutosPDV.getModel();
        modelProdutos = new ModelProdutos();
        //modelo.setNumRows(0);

        if (e.getKeyCode() == java.awt.event.KeyEvent.VK_F1) {
            try {
                //modelProdutos = controllerProdutos.getProdutosController(Integer.parseInt(jTextFieldCodigoProdutoPDV.getText()));
                modelProdutos = controllerProdutos.getProdutosController(jTextFieldCodigoProdutoPDV.getText());
                modelo.addRow(new Object[]{
                    modelo.getRowCount() + 1,
                    modelProdutos.getIdProduto(),
                    modelProdutos.getProdNome(),
                    qtd,
                    modelProdutos.getProdValor(),
                    modelProdutos.getProdValor() * qtd
                });
                somaValorTotal();
                qtd = 1;
            } catch (Exception f) {
                System.out.println("Entrou no catch");
                JOptionPane.showMessageDialog(this, "Código do Produto INCORRETO ou VAZIO", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            jTextFieldCodigoProdutoPDV.setText("");
        }
    }

    private void salvarVendas() {
        int codigoProduto, qtdVenda, codigoVenda;
        modelVendas = new ModelVendas();
        modelVendas.setCliente(1);
        try {
            modelVendas.setVenDataVenda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            Logger.getLogger(PDV.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelVendas.setVenDesconto(Double.parseDouble(jTextFieldDescontoVendaPDV.getText()));
        modelVendas.setVenValorBruto(totalBrutoVendaPDV);
        modelVendas.setVenValorLiquido(totalLiquidoVendaPDV);

        //salva a venda
        codigoVenda = controllerVendas.salvarVendasController(modelVendas);
        for (int i = 0; i < jTableListaProdutosPDV.getRowCount(); i++) {
            codigoProduto = (int) jTableListaProdutosPDV.getValueAt(i, 1);
            qtdVenda = Integer.parseInt(jTableListaProdutosPDV.getValueAt(i, 3).toString());
            modelVendasProdutos = new ModelVendasProdutos();
            modelProdutos = new ModelProdutos();
            modelVendasProdutos.setProduto(codigoProduto);
            modelVendasProdutos.setVendas(codigoVenda);
            modelVendasProdutos.setVenProValor((double) jTableListaProdutosPDV.getValueAt(i, 4));
            modelVendasProdutos.setVenProQuantidade(qtdVenda);
            listaModelVendasProdutoses.add(modelVendasProdutos);
            //subtrai a quantidade vendida no estoque
            modelProdutos.setIdProduto(codigoProduto);
            modelProdutos.setProdEstoque(controllerProdutos.getProdutosController(codigoProduto).getProdEstoque()
                    - qtdVenda);
            listaModelProdutos.add(modelProdutos);
        }

        //salvar os produtos da venda e alterar o estoque
        if (controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutoses)) {
            //JOptionPane.showMessageDialog(this, "Venda Concluida com SUCESSO", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            controllerProdutos.alterarEstoqueProdutosController(listaModelProdutos);//Alterar o estoque no banco;
            limparVendas();
        } else {
            //JOptionPane.showMessageDialog(this, "Erro ao Concluir a Venda", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        jFormattedTextFieldValorBrutoVendaPDV.setText("");
    }

    private void limparVendas() {
        jTextFieldCodigoProdutoPDV.setText("");
        jFormattedTextFieldValorBrutoVendaPDV.setText("");
        jTextFieldDescontoVendaPDV.setText("0");
        jFormattedTextFieldValorLiquidoVendaPDV.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jTableListaProdutosPDV.getModel();
        modelo.setNumRows(0);
    }

    private void mudarQuantidadeProduto() {
        int linha = jTableListaProdutosPDV.getSelectedRow();
        int quantidade = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade desejada: "));
        Double valor = (double) jTableListaProdutosPDV.getValueAt(linha, 4);
        Double total = quantidade * valor;
        jTableListaProdutosPDV.setValueAt(quantidade, linha, 3);//setando a nova quantidade do item
        jTableListaProdutosPDV.setValueAt(total, linha, 5);//setando o novo valor total
        somaValorTotal();
        jTextFieldCodigoProdutoPDV.requestFocus();
    }

    private void setarOperador() {
        jLabelOperador.setText(modelSessaoUsuario.nome);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldValorBrutoVendaPDV;
    private javax.swing.JFormattedTextField jFormattedTextFieldValorLiquidoVendaPDV;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelOperador;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuComandosPDV;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAlterarQuantidadePDV;
    private javax.swing.JMenuItem jMenuItemExcluirProduto;
    private javax.swing.JMenuItem jMenuItemFinalizarVendaPDV;
    private javax.swing.JMenuItem jMenuItemIncluirProduto;
    private javax.swing.JMenuItem jMenuItemPesquisarProdutosPDV;
    private javax.swing.JMenu jMenuSairPDV;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableListaProdutosPDV;
    private javax.swing.JTextField jTextFieldCodigoProdutoPDV;
    private javax.swing.JTextField jTextFieldDescontoVendaPDV;
    private componentes.UJPanelImagem uJPanelImagem6;
    // End of variables declaration//GEN-END:variables
}
