/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasProdutos;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ModelProdutos;
import model.ModelSessaoUsuario;
import model.ModelVendas;
import model.ModelVendasProdutos;
import util.BLDatas;
import util.BLMascaras;

/**
 *
 * @author jefer
 */
public class PDV extends javax.swing.JFrame {

    BLDatas bLDatas = new BLDatas();
    BLMascaras bLMascaras = new BLMascaras();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ControllerVendas controllerVendas = new ControllerVendas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    ModelVendas modelVendas = new ModelVendas();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ModelSessaoUsuario modelSessaoUsuario = new ModelSessaoUsuario();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutoses = new ArrayList<>();
    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();
    private PagamentoPDV viewPagamentoPDV;
    int qtd;
    Double totalLiquidoVendaPDV, totalBrutoVendaPDV;

    /**
     * Creates new form PDV
     */
    public PDV() {
        initComponents();
        setarOperador();
        setExtendedState(MAXIMIZED_BOTH);
        jTextFieldDescontoVendaPDV.setText("0");
        jTextFieldCodigoProdutoPDV.requestFocus();//inicia com o foco no jTextFieldCodigoProdutoPDV
        qtd = 1;
        this.viewPagamentoPDV = new PagamentoPDV(this, true);
        jLabelStatus.setText("ABERTO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableListaProdutosPDV = new javax.swing.JTable();
        jTextFieldCodigoProdutoPDV = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelOperador = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextFieldValorBrutoVendaPDV = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jFormattedTextFieldValorLiquidoVendaPDV = new javax.swing.JFormattedTextField();
        jTextFieldDescontoVendaPDV = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuSairPDV = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuComandosPDV = new javax.swing.JMenu();
        jMenuItemIncluirProduto = new javax.swing.JMenuItem();
        jMenuItemExcluirProduto = new javax.swing.JMenuItem();
        jMenuItemAlterarQuantidadePDV = new javax.swing.JMenuItem();
        jMenuItemFinalizarVendaPDV = new javax.swing.JMenuItem();
        jMenuItemPesquisarProdutosPDV = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 255, 153));

        jTableListaProdutosPDV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Codigo", "Nome", "Quantidade", "Valor Unit.", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableListaProdutosPDV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableListaProdutosPDVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableListaProdutosPDV);
        if (jTableListaProdutosPDV.getColumnModel().getColumnCount() > 0) {
            jTableListaProdutosPDV.getColumnModel().getColumn(0).setMinWidth(50);
            jTableListaProdutosPDV.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTableListaProdutosPDV.getColumnModel().getColumn(0).setMaxWidth(50);
            jTableListaProdutosPDV.getColumnModel().getColumn(1).setMinWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(1).setMaxWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(3).setMinWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(3).setMaxWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(4).setMinWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(4).setMaxWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(5).setMinWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(5).setPreferredWidth(100);
            jTableListaProdutosPDV.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        jTextFieldCodigoProdutoPDV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCodigoProdutoPDVKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                    .addComponent(jTextFieldCodigoProdutoPDV))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodigoProdutoPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("OPERADOR: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("STATUS: ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("CAIXA: ");

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelStatus.setText("STATUS");

        jLabelOperador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelOperador.setText("OPERADOR");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("01");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabelStatus)
                    .addComponent(jLabelOperador))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelOperador))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelStatus))
                .addGap(24, 24, 24))
        );

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("COMANDOS");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel10.setText("F4 - Finalizar Venda");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel11.setText("F3 - Alterar Quantidade");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel12.setText("F5 - Pesquisar Produto");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel13.setText("F9 - Sair");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("DESCONTO (em %)");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("VALOR TOTAL");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel16.setText("F2 - Excluir Produto");

        jFormattedTextFieldValorBrutoVendaPDV.setEditable(false);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel17.setText("F1 - Incluir Produto");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("TOTAL A PAGAR");

        jFormattedTextFieldValorLiquidoVendaPDV.setEditable(false);

        jTextFieldDescontoVendaPDV.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel15))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jLabel14)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldValorBrutoVendaPDV)
                            .addComponent(jFormattedTextFieldValorLiquidoVendaPDV)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addGap(68, 68, 68))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldDescontoVendaPDV)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDescontoVendaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldValorBrutoVendaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldValorLiquidoVendaPDV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuSairPDV.setText("Arquivos");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F9, 0));
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuSairPDV.add(jMenuItem1);

        jMenuBar1.add(jMenuSairPDV);

        jMenuComandosPDV.setText("Comandos");

        jMenuItemIncluirProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItemIncluirProduto.setText("Incluir Produto");
        jMenuItemIncluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIncluirProdutoActionPerformed(evt);
            }
        });
        jMenuComandosPDV.add(jMenuItemIncluirProduto);

        jMenuItemExcluirProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItemExcluirProduto.setText("Excluir Produto");
        jMenuItemExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExcluirProdutoActionPerformed(evt);
            }
        });
        jMenuComandosPDV.add(jMenuItemExcluirProduto);

        jMenuItemAlterarQuantidadePDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F3, 0));
        jMenuItemAlterarQuantidadePDV.setText("Alterar Quantidade");
        jMenuItemAlterarQuantidadePDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlterarQuantidadePDVActionPerformed(evt);
            }
        });
        jMenuComandosPDV.add(jMenuItemAlterarQuantidadePDV);

        jMenuItemFinalizarVendaPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        jMenuItemFinalizarVendaPDV.setText("Finalizar Venda");
        jMenuItemFinalizarVendaPDV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFinalizarVendaPDVActionPerformed(evt);
            }
        });
        jMenuComandosPDV.add(jMenuItemFinalizarVendaPDV);

        jMenuItemPesquisarProdutosPDV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F5, 0));
        jMenuItemPesquisarProdutosPDV.setText("Pesquisar Produtos");
        jMenuComandosPDV.add(jMenuItemPesquisarProdutosPDV);

        jMenuBar1.add(jMenuComandosPDV);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void somaValorTotal() {
        double soma = 0, valor, liquido, desconto;
        int cont = jTableListaProdutosPDV.getRowCount();

        for (int i = 0; i < cont; i++) {
            valor = (double) jTableListaProdutosPDV.getValueAt(i, 5);
            soma += valor;
        }
        totalBrutoVendaPDV = bLMascaras.arredondamentoComPontoDuasCasasDouble(soma);
        desconto = Integer.parseInt(jTextFieldDescontoVendaPDV.getText());
        System.err.println("Valor do Desconto :" + desconto);
        liquido = soma - ((desconto / 100) * soma);
        System.err.println("Valor do Liquido :" + liquido);
        DecimalFormat df = new DecimalFormat("#,###.00");//formata as casas decimais de um Double
        jFormattedTextFieldValorBrutoVendaPDV.setText("R$: " + String.valueOf(df.format(soma)));
        jFormattedTextFieldValorLiquidoVendaPDV.setText("R$: " + String.valueOf(df.format(liquido)));
    }

    private void pegarCodigo(java.awt.event.KeyEvent e) {
        jLabelStatus.setText("OCUPADO");
        DefaultTableModel modelo = (DefaultTableModel) jTableListaProdutosPDV.getModel();
        modelProdutos = new ModelProdutos();
        //modelo.setNumRows(0);

        if (e.getKeyCode() == java.awt.event.KeyEvent.VK_F1) {
            try {
                System.out.println("Entrou no try");
                modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(jTextFieldCodigoProdutoPDV.getText()));
                System.err.println("Pressionando ENTER: " + qtd);
                modelo.addRow(new Object[]{
                    modelo.getRowCount() + 1,
                    modelProdutos.getIdProduto(),
                    modelProdutos.getProdNome(),
                    qtd,
                    modelProdutos.getProdValor(),
                    modelProdutos.getProdValor() * qtd
                });
                somaValorTotal();
                qtd = 1;
            } catch (Exception f) {
                System.out.println("Entrou no catch");
                JOptionPane.showMessageDialog(this, "Código do Produto INCORRETO ou VAZIO", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
            jTextFieldCodigoProdutoPDV.setText("");
        }
    }

    private void salvarVendas() {
        int codigoProduto, qtdVenda, codigoVenda;
        modelVendas = new ModelVendas();
        modelVendas.setCliente(1);
        try {
            modelVendas.setVenDataVenda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception ex) {
            Logger.getLogger(PDV.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelVendas.setVenDesconto(Double.parseDouble(jTextFieldDescontoVendaPDV.getText()));
        modelVendas.setVenValorBruto(totalBrutoVendaPDV);
        modelVendas.setVenValorLiquido(totalLiquidoVendaPDV);

        //salva a venda
        codigoVenda = controllerVendas.salvarVendasController(modelVendas);
        for (int i = 0; i < jTableListaProdutosPDV.getRowCount(); i++) {
            codigoProduto = (int) jTableListaProdutosPDV.getValueAt(i, 1);
            qtdVenda = Integer.parseInt(jTableListaProdutosPDV.getValueAt(i, 3).toString());
            modelVendasProdutos = new ModelVendasProdutos();
            modelProdutos = new ModelProdutos();
            modelVendasProdutos.setProduto(codigoProduto);
            modelVendasProdutos.setVendas(codigoVenda);
            modelVendasProdutos.setVenProValor((double) jTableListaProdutosPDV.getValueAt(i, 4));
            modelVendasProdutos.setVenProQuantidade(qtdVenda);
            listaModelVendasProdutoses.add(modelVendasProdutos);
            //subtrai a quantidade vendida no estoque
            modelProdutos.setIdProduto(codigoProduto);
            modelProdutos.setProdEstoque(controllerProdutos.retornarProdutoController(codigoProduto).getProdEstoque()
                    - qtdVenda);
            listaModelProdutos.add(modelProdutos);
        }

        //salvar os produtos da venda e alterar o estoque
        if (controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutoses)) {
            //JOptionPane.showMessageDialog(this, "Venda Concluida com SUCESSO", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            controllerProdutos.alterarEstoqueProdutoControler(listaModelProdutos);//Alterar o estoque no banco;
            limparVendas();
        } else {
            //JOptionPane.showMessageDialog(this, "Erro ao Concluir a Venda", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
        jFormattedTextFieldValorBrutoVendaPDV.setText("");
    }

    private void limparVendas() {
        jTextFieldCodigoProdutoPDV.setText("");
        jFormattedTextFieldValorBrutoVendaPDV.setText("");
        jTextFieldDescontoVendaPDV.setText("0");
        jFormattedTextFieldValorLiquidoVendaPDV.setText("");
        DefaultTableModel modelo = (DefaultTableModel) jTableListaProdutosPDV.getModel();
        modelo.setNumRows(0);
    }

    private void mudarQuantidadeProduto() {
        int linha = jTableListaProdutosPDV.getSelectedRow();
        int quantidade = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade desejada: "));
        Double valor = (double) jTableListaProdutosPDV.getValueAt(linha, 4);
        Double total = quantidade * valor;
        jTableListaProdutosPDV.setValueAt(quantidade, linha, 3);//setando a nova quantidade do item
        jTableListaProdutosPDV.setValueAt(total, linha, 5);//setando o novo valor total
        somaValorTotal();
        jTextFieldCodigoProdutoPDV.requestFocus();
    }

    private void setarOperador() {
        jLabelOperador.setText(modelSessaoUsuario.nome);
    }

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItemFinalizarVendaPDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFinalizarVendaPDVActionPerformed
        // TODO add your handling code here:
        try {
            viewPagamentoPDV.setValorTotal(Float.parseFloat(totalBrutoVendaPDV.toString()));
            viewPagamentoPDV.preencherCampos();
            viewPagamentoPDV.setVisible(true);

            jTextFieldDescontoVendaPDV.setText(String.valueOf(viewPagamentoPDV.getDesconto()));//pega o valor do desconto na view PagamentoPDV
            totalLiquidoVendaPDV = bLMascaras.arredondamentoComPontoDuasCasasDouble(Double.parseDouble(String.valueOf(viewPagamentoPDV.getTotalPagar())));//pega o valor do total a pagar na view PagamentoPDV e seta na totalLiquidoVendaPDV

            if (viewPagamentoPDV.isPago()) {
                salvarVendas();
                jLabelStatus.setText("ABERTO");
                limparVendas();
            } else {
                jTextFieldDescontoVendaPDV.setText(String.valueOf(viewPagamentoPDV.getDesconto()));//pega o valor do desconto na view PagamentoPDV
                DecimalFormat df = new DecimalFormat("#,###.00");//formata as casas decimais de um Double
                jFormattedTextFieldValorBrutoVendaPDV.setText("R$: " + String.valueOf(df.format(totalBrutoVendaPDV)));//pega o valor do total na variavel global
                jFormattedTextFieldValorLiquidoVendaPDV.setText("R$: " + String.valueOf(df.format(totalLiquidoVendaPDV)));//pega o valor do total A PAGAR na variavel global
                JOptionPane.showMessageDialog(this, "Você nao concluiu o Pagamento", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItemFinalizarVendaPDVActionPerformed

    private void jMenuItemAlterarQuantidadePDVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlterarQuantidadePDVActionPerformed
        // TODO add your handling code here:
        qtd = Integer.parseInt(JOptionPane.showInputDialog("Informe a quantidade desejada: "));
        System.err.println("Pressionando F3: " + qtd);
    }//GEN-LAST:event_jMenuItemAlterarQuantidadePDVActionPerformed

    private void jTableListaProdutosPDVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableListaProdutosPDVMouseClicked
        // TODO add your handling code here:
        mudarQuantidadeProduto();
    }//GEN-LAST:event_jTableListaProdutosPDVMouseClicked

    private void jMenuItemExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExcluirProdutoActionPerformed
        // TODO add your handling code here:
        int qtdLinha = jTableListaProdutosPDV.getRowCount();
        System.out.println(qtdLinha);
        if (qtdLinha < 1) {
            JOptionPane.showMessageDialog(this, "Erro ao Excluir a Venda, Nenhum Item na Tabela", "ERRO", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) jTableListaProdutosPDV.getModel();
            int linha = Integer.parseInt(JOptionPane.showInputDialog("Informe o ITEM que deseja excluir: "));
            modelo.removeRow(linha - 1);
            somaValorTotal();
            for (int i = 0; i < qtdLinha; i++) {
                modelo.setValueAt(i + 1, i, 0);
            }
        }
    }//GEN-LAST:event_jMenuItemExcluirProdutoActionPerformed

    private void jTextFieldCodigoProdutoPDVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProdutoPDVKeyReleased
        // TODO add your handling code here:
        pegarCodigo(evt);
    }//GEN-LAST:event_jTextFieldCodigoProdutoPDVKeyReleased

    private void jMenuItemIncluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIncluirProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemIncluirProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldValorBrutoVendaPDV;
    private javax.swing.JFormattedTextField jFormattedTextFieldValorLiquidoVendaPDV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelOperador;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuComandosPDV;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemAlterarQuantidadePDV;
    private javax.swing.JMenuItem jMenuItemExcluirProduto;
    private javax.swing.JMenuItem jMenuItemFinalizarVendaPDV;
    private javax.swing.JMenuItem jMenuItemIncluirProduto;
    private javax.swing.JMenuItem jMenuItemPesquisarProdutosPDV;
    private javax.swing.JMenu jMenuSairPDV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableListaProdutosPDV;
    private javax.swing.JTextField jTextFieldCodigoProdutoPDV;
    private javax.swing.JTextField jTextFieldDescontoVendaPDV;
    // End of variables declaration//GEN-END:variables
}
