/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerFornecedor;
import controller.ControllerProdutos;
import controller.ControllerVendas;
import controllerRelatorios.ControllerRelatorioCliente;
import controllerRelatorios.ControllerRelatorioProduto;
import controllerRelatorios.ControllerRelatorioVenda;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.ModelCliente;
import model.ModelFornecedor;
import model.ModelProdutos;
import model.ModelVendas;

/**
 *
 * @author jefer
 */
public class Relatorios extends javax.swing.JFrame {

    ControllerRelatorioCliente controllerRelatorioCliente = new ControllerRelatorioCliente();
    ControllerRelatorioProduto controllerRelatorioProduto = new ControllerRelatorioProduto();
    ControllerRelatorioVenda controllerRelatorioVenda = new ControllerRelatorioVenda();
    ControllerCliente controllerCliente = new ControllerCliente();
    ControllerFornecedor controllerFornecedor = new ControllerFornecedor();
    ModelFornecedor modelFornecedor = new ModelFornecedor();
    ArrayList<ModelFornecedor> listaModelFornecedors = new ArrayList<>();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();
    ControllerVendas controllerVendas = new ControllerVendas();
    ModelVendas modelVendas = new ModelVendas();
    ArrayList<ModelVendas> listaModelVendas = new ArrayList<>();
    int codigo;
    private Object bLDatas;

    /**
     * Creates new form Relatorios
     */
    public Relatorios() {
        initComponents();
        listarClientes();
        listarVendasPorCliente();
        listarProdutos();
        listarFornecedores();
        carregarVendas();
        mudarFonteTabela();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../imagens/carrinho-de-compras.png")));
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Maiandra GD", Font.PLAIN, 35)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButtonRelatorioTodosProdutos = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        uJComboBoxListarProdutos = new componentes.UJComboBox();
        jButtonRelatorioUmProduto = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        uJComboBoxListarFornecedores = new componentes.UJComboBox();
        jButtonRelatorioProdutoPorFornecedor = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButtonRelatorioTodosClientes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        uJComboBoxListarClientes = new componentes.UJComboBox();
        jButtonRelatorioUmCliente = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jButtonRelatorioTodosVendas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        uJComboBoxListarClientesVendas = new componentes.UJComboBox();
        jButtonRelatorioVendaPorCliente = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jButtonRelatorioUmaVendaPorCliente = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVendaCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Vendas - Emissão de Relatórios");
        setPreferredSize(new java.awt.Dimension(1500, 758));
        setResizable(false);
        setSize(new java.awt.Dimension(1500, 800));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PRODUTO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 24))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 306));

        jPanel10.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Todos os Produtos");

        jButtonRelatorioTodosProdutos.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonRelatorioTodosProdutos.setText("Gerar");
        jButtonRelatorioTodosProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioTodosProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jButtonRelatorioTodosProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(156, 156, 156))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jButtonRelatorioTodosProdutos)
                .addContainerGap())
        );

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Apenas um Produto");

        uJComboBoxListarProdutos.setMaximumRowCount(20);
        uJComboBoxListarProdutos.setAutocompletar(true);
        uJComboBoxListarProdutos.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N

        jButtonRelatorioUmProduto.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonRelatorioUmProduto.setText("Gerar");
        jButtonRelatorioUmProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioUmProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJComboBoxListarProdutos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButtonRelatorioUmProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                .addGap(156, 156, 156))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uJComboBoxListarProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRelatorioUmProduto)
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(204, 255, 204));

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Produto Por Fornecedor");

        uJComboBoxListarFornecedores.setMaximumRowCount(20);
        uJComboBoxListarFornecedores.setAutocompletar(true);
        uJComboBoxListarFornecedores.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N

        jButtonRelatorioProdutoPorFornecedor.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonRelatorioProdutoPorFornecedor.setText("Gerar");
        jButtonRelatorioProdutoPorFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioProdutoPorFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJComboBoxListarFornecedores, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addComponent(jButtonRelatorioProdutoPorFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(156, 156, 156))
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uJComboBoxListarFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonRelatorioProdutoPorFornecedor)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CLIENTE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 24))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 306));

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));

        jButtonRelatorioTodosClientes.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonRelatorioTodosClientes.setText("Gerar");
        jButtonRelatorioTodosClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioTodosClientesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Todos os Clientes");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jButtonRelatorioTodosClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(165, 165, 165))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButtonRelatorioTodosClientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Apenas um Cliente");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        uJComboBoxListarClientes.setMaximumRowCount(20);
        uJComboBoxListarClientes.setAutocompletar(true);
        uJComboBoxListarClientes.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N

        jButtonRelatorioUmCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonRelatorioUmCliente.setText("Gerar");
        jButtonRelatorioUmCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelatorioUmCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioUmClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJComboBoxListarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jButtonRelatorioUmCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGap(169, 169, 169))
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uJComboBoxListarClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonRelatorioUmCliente)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "VENDAS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Maiandra GD", 1, 24))); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 306));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(429, 113));

        jButtonRelatorioTodosVendas.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonRelatorioTodosVendas.setText("Gerar");
        jButtonRelatorioTodosVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioTodosVendasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Todos as Vendas");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jButtonRelatorioTodosVendas, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(154, 154, 154))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jButtonRelatorioTodosVendas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(204, 255, 204));

        jLabel8.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Filtrar por Cliente");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        uJComboBoxListarClientesVendas.setMaximumRowCount(20);
        uJComboBoxListarClientesVendas.setAutocompletar(true);
        uJComboBoxListarClientesVendas.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        uJComboBoxListarClientesVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uJComboBoxListarClientesVendasActionPerformed(evt);
            }
        });

        jButtonRelatorioVendaPorCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonRelatorioVendaPorCliente.setText("Gerar");
        jButtonRelatorioVendaPorCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelatorioVendaPorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioVendaPorClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(uJComboBoxListarClientesVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButtonRelatorioVendaPorCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(146, 146, 146))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uJComboBoxListarClientesVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRelatorioVendaPorCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));

        jLabel9.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Uma Venda por Cliente");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButtonRelatorioUmaVendaPorCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonRelatorioUmaVendaPorCliente.setText("Gerar");
        jButtonRelatorioUmaVendaPorCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRelatorioUmaVendaPorCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRelatorioUmaVendaPorClienteActionPerformed(evt);
            }
        });

        jTableVendaCliente.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTableVendaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo da Venda", "Data da Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableVendaCliente.setMinimumSize(new java.awt.Dimension(15, 0));
        jTableVendaCliente.setRowHeight(30);
        jScrollPane1.setViewportView(jTableVendaCliente);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jButtonRelatorioUmaVendaPorCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addGap(167, 167, 167))
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRelatorioUmaVendaPorCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 452, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 448, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addGap(20, 20, 20)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mudarFonteTabela() {// muda a fonte da tabela de vendas
        JTableHeader cabecalho = jTableVendaCliente.getTableHeader();
        cabecalho.setFont(new Font("Maiandra GD", Font.PLAIN, 24));
    }

    //Lista os clientes para preencher o uJComboBoxNomeClienteProdutosVenda
    private void listarClientes() {
        listaModelClientes = controllerCliente.getListaClienteController();
        uJComboBoxListarClientes.removeAllItems();
        for (int i = 0; i < listaModelClientes.size(); i++) {
            uJComboBoxListarClientes.addItem(listaModelClientes.get(i).getCliNome());
        }
    }

    private void listarProdutos() {
        listaModelProdutos = controllerProdutos.getListaProdutosController();
        uJComboBoxListarProdutos.removeAllItems();
        for (int i = 0; i < listaModelProdutos.size(); i++) {
            uJComboBoxListarProdutos.addItem(listaModelProdutos.get(i).getProdNome());
        }
    }

    private void listarVendasPorCliente() {
        listaModelClientes = controllerCliente.getListaClienteController();
        uJComboBoxListarClientesVendas.removeAllItems();
        for (int i = 0; i < listaModelClientes.size(); i++) {
            uJComboBoxListarClientesVendas.addItem(listaModelClientes.get(i).getCliNome());
        }
    }

    private void listarFornecedores() {
        listaModelFornecedors = controllerFornecedor.getListaFornecedorController();
        uJComboBoxListarFornecedores.removeAllItems();
        for (int i = 0; i < listaModelFornecedors.size(); i++) {
            uJComboBoxListarFornecedores.addItem(listaModelFornecedors.get(i).getNome_fantasia());
        }
    }

    private void carregarVendas() {
        DefaultTableModel modelo = (DefaultTableModel) jTableVendaCliente.getModel();
        modelCliente = controllerCliente.getClienteController(uJComboBoxListarClientesVendas.getSelectedItem().toString());
        codigo = modelCliente.getIdCliente();
        listaModelVendas = controllerRelatorioVenda.getVendasPorClienteController(codigo);
        modelo.setNumRows(0);//seta o numero de linhas em ZERO para nao duplicar na tabela
        int cont = listaModelVendas.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelVendas.get(i).getIdVenda(),
                listaModelVendas.get(i).getVenDataVenda()
            });
        }
    }

    private void jButtonRelatorioUmProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioUmProdutoActionPerformed
        // TODO add your handling code here:
        modelProdutos = controllerProdutos.getProdutoController(uJComboBoxListarProdutos.getSelectedItem().toString());
        codigo = modelProdutos.getIdProduto();
        controllerRelatorioProduto.gerarRelatorioUmProdutoController(codigo);
    }//GEN-LAST:event_jButtonRelatorioUmProdutoActionPerformed

    private void jButtonRelatorioTodosProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioTodosProdutosActionPerformed
        // TODO add your handling code here:
        controllerRelatorioProduto.gerarRelatorioTodosProdutosController();
    }//GEN-LAST:event_jButtonRelatorioTodosProdutosActionPerformed

    private void jButtonRelatorioUmClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioUmClienteActionPerformed
        // TODO add your handling code here:
        modelCliente = controllerCliente.getClienteController(uJComboBoxListarClientes.getSelectedItem().toString());
        codigo = modelCliente.getIdCliente();
        controllerRelatorioCliente.gerarRelatorioUmClientesController(codigo);
    }//GEN-LAST:event_jButtonRelatorioUmClienteActionPerformed

    private void jButtonRelatorioTodosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioTodosClientesActionPerformed
        // TODO add your handling code here:
        controllerRelatorioCliente.gerarRelatorioTodosClientesController();
    }//GEN-LAST:event_jButtonRelatorioTodosClientesActionPerformed

    private void jButtonRelatorioTodosVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioTodosVendasActionPerformed
        // TODO add your handling code here:
        controllerRelatorioVenda.gerarRelatorioTodasVendasController();
    }//GEN-LAST:event_jButtonRelatorioTodosVendasActionPerformed

    private void jButtonRelatorioVendaPorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioVendaPorClienteActionPerformed
        // TODO add your handling code here:
        modelCliente = controllerCliente.getClienteController(uJComboBoxListarClientesVendas.getSelectedItem().toString());
        codigo = modelCliente.getIdCliente();
        controllerRelatorioVenda.gerarRelatorioVendasPorClienteController(codigo);
    }//GEN-LAST:event_jButtonRelatorioVendaPorClienteActionPerformed

    private void jButtonRelatorioUmaVendaPorClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioUmaVendaPorClienteActionPerformed
        // TODO add your handling code here:
        modelCliente = controllerCliente.getClienteController(uJComboBoxListarClientesVendas.getSelectedItem().toString());
        codigo = modelCliente.getIdCliente();
        int linha = jTableVendaCliente.getSelectedRow();
        String data = jTableVendaCliente.getValueAt(linha, 1).toString();
        int idVenda = (int) jTableVendaCliente.getValueAt(linha, 0);
        //Chamar a função que vai imprimir a venda, passando o codigo do cliente, data da venda e codigo da venda
        controllerRelatorioVenda.gerarRelatorioUmaVendaPorClienteController(codigo, data, idVenda);
    }//GEN-LAST:event_jButtonRelatorioUmaVendaPorClienteActionPerformed

    private void uJComboBoxListarClientesVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uJComboBoxListarClientesVendasActionPerformed
        // TODO add your handling code here:
        carregarVendas();
    }//GEN-LAST:event_uJComboBoxListarClientesVendasActionPerformed

    private void jButtonRelatorioProdutoPorFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRelatorioProdutoPorFornecedorActionPerformed
        // TODO add your handling code here:
        modelFornecedor = controllerFornecedor.getFornecedorController(uJComboBoxListarFornecedores.getSelectedItem().toString());
        codigo = modelFornecedor.getId_fornecedor();
        controllerRelatorioProduto.gerarRelatorioProdutosPorFornecedorController(codigo);
    }//GEN-LAST:event_jButtonRelatorioProdutoPorFornecedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relatorios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Relatorios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRelatorioProdutoPorFornecedor;
    private javax.swing.JButton jButtonRelatorioTodosClientes;
    private javax.swing.JButton jButtonRelatorioTodosProdutos;
    private javax.swing.JButton jButtonRelatorioTodosVendas;
    private javax.swing.JButton jButtonRelatorioUmCliente;
    private javax.swing.JButton jButtonRelatorioUmProduto;
    private javax.swing.JButton jButtonRelatorioUmaVendaPorCliente;
    private javax.swing.JButton jButtonRelatorioVendaPorCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVendaCliente;
    private componentes.UJComboBox uJComboBoxListarClientes;
    private componentes.UJComboBox uJComboBoxListarClientesVendas;
    private componentes.UJComboBox uJComboBoxListarFornecedores;
    private componentes.UJComboBox uJComboBoxListarProdutos;
    // End of variables declaration//GEN-END:variables
}
