/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerUsuario;
import java.awt.Font;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import model.ModelUsuario;

/**
 *
 * @author jefer
 */
public class Usuario extends javax.swing.JFrame {

    ControllerUsuario controllerUsuario = new ControllerUsuario();
    ModelUsuario modelUsuario = new ModelUsuario();
    ArrayList<ModelUsuario> listaModelUsuario = new ArrayList<>();
    String salvarAlterar; //Varilavel global que vai ser usada no if do botao salvar para determinar se é para alterar ou salvar um novo usuario

    /**
     * Creates new form ViewUsuario
     */
    public Usuario() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        carregarUsuarios();
        habilitarDesabilitar(false);
        carregarIcone();
        UIManager.put("OptionPane.messageFont", new FontUIResource(new Font("Maiandra GD", Font.PLAIN, 35)));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCodigoUsuario = new javax.swing.JTextField();
        jTextFieldNomeUsuario = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuario = new javax.swing.JTable();
        jButtonNovoUsuario = new javax.swing.JButton();
        jButtonAlterarUsuario = new javax.swing.JButton();
        jButtonSalvarUsuario = new javax.swing.JButton();
        jButtonCancelarUsuario = new javax.swing.JButton();
        jButtonExcluirUsuario = new javax.swing.JButton();
        jTextFieldLoginUsuario = new javax.swing.JTextField();
        jTextFieldSenhaUsuario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Vendas - Cadastro e Busca de Usuarios");
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel3.setText("Código");

        jLabel12.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel12.setText("Nome");

        jTextFieldCodigoUsuario.setEditable(false);
        jTextFieldCodigoUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldCodigoUsuario.setEnabled(false);
        jTextFieldCodigoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoUsuarioActionPerformed(evt);
            }
        });

        jTextFieldNomeUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeUsuarioActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel11.setText("Login");

        jLabel10.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jLabel10.setText("Senha");

        jTableUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTableUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Login"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuario.setRowHeight(30);
        jScrollPane1.setViewportView(jTableUsuario);
        if (jTableUsuario.getColumnModel().getColumnCount() > 0) {
            jTableUsuario.getColumnModel().getColumn(0).setMinWidth(150);
            jTableUsuario.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableUsuario.getColumnModel().getColumn(0).setMaxWidth(150);
        }

        jButtonNovoUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonNovoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/papel-de-texto.png"))); // NOI18N
        jButtonNovoUsuario.setText("Novo");
        jButtonNovoUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNovoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoUsuario.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonNovoUsuario.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoUsuarioActionPerformed(evt);
            }
        });

        jButtonAlterarUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonAlterarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/editar.png"))); // NOI18N
        jButtonAlterarUsuario.setText("Alterar");
        jButtonAlterarUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAlterarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlterarUsuario.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonAlterarUsuario.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonAlterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarUsuarioActionPerformed(evt);
            }
        });

        jButtonSalvarUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonSalvarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/disquete.png"))); // NOI18N
        jButtonSalvarUsuario.setText("Salvar");
        jButtonSalvarUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvarUsuario.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonSalvarUsuario.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonSalvarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarUsuarioActionPerformed(evt);
            }
        });

        jButtonCancelarUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonCancelarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/proibido.png"))); // NOI18N
        jButtonCancelarUsuario.setText("Cancelar");
        jButtonCancelarUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancelarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelarUsuario.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonCancelarUsuario.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonCancelarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarUsuarioActionPerformed(evt);
            }
        });

        jButtonExcluirUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jButtonExcluirUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/cancelar.png"))); // NOI18N
        jButtonExcluirUsuario.setText("Excluir");
        jButtonExcluirUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExcluirUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirUsuario.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonExcluirUsuario.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonExcluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirUsuarioActionPerformed(evt);
            }
        });

        jTextFieldLoginUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldLoginUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoginUsuarioActionPerformed(evt);
            }
        });

        jTextFieldSenhaUsuario.setFont(new java.awt.Font("Maiandra GD", 0, 24)); // NOI18N
        jTextFieldSenhaUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldSenhaUsuarioKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1217, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldNomeUsuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTextFieldLoginUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(145, 145, 145))
                            .addComponent(jTextFieldSenhaUsuario)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldLoginUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSenhaUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void carregarIcone() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagens/carrinho_de_compras.png")));
    }

//Carregar Usuarios na Tabela
    private void carregarUsuarios() {
        listaModelUsuario = controllerUsuario.getListaUsuarioController();
        DefaultTableModel modelo = (DefaultTableModel) jTableUsuario.getModel();
        modelo.setNumRows(0);

        int cont = listaModelUsuario.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelUsuario.get(i).getIdUsuario(),
                listaModelUsuario.get(i).getUsNome(),
                listaModelUsuario.get(i).getUsLogin()
            });
        }
        JTableHeader cabecalho = jTableUsuario.getTableHeader();
        cabecalho.setFont(new Font("Maiandra GD", Font.PLAIN, 24));
    }

//Limpar os campos do Formulario
    private void limparCampos() {
        jTextFieldCodigoUsuario.setText("");
        jTextFieldNomeUsuario.setText("");
        jTextFieldLoginUsuario.setText("");
        jTextFieldSenhaUsuario.setText("");
    }

    //Habilitar e desabilitar os campos e botoes do Formulario
    private void habilitarDesabilitar(boolean condicao) {
        jTextFieldNomeUsuario.setEnabled(condicao);
        jTextFieldLoginUsuario.setEnabled(condicao);
        jTextFieldSenhaUsuario.setEnabled(condicao);
        jButtonSalvarUsuario.setEnabled(condicao);
    }

    private void salvarAlterar() {
        try {
            modelUsuario.setIdUsuario(Integer.parseInt(jTextFieldCodigoUsuario.getText()));
        } catch (NumberFormatException e) {
        }

        if (!jTextFieldNomeUsuario.getText().isEmpty() && !jTextFieldLoginUsuario.getText().isEmpty()
                && !jTextFieldSenhaUsuario.getText().isEmpty()) {
            modelUsuario.setUsNome(jTextFieldNomeUsuario.getText().toUpperCase());
            modelUsuario.setUsLogin(jTextFieldLoginUsuario.getText().toUpperCase());
            modelUsuario.setUsSenha(jTextFieldSenhaUsuario.getText().toUpperCase());

            if (salvarAlterar.equals("salvar")) {
                if (controllerUsuario.salvarUsuarioController(modelUsuario) > 0) {
                    JOptionPane.showMessageDialog(this, "Usuario Salvo com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    carregarUsuarios();
                    limparCampos();
                    habilitarDesabilitar(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao Salvar o Usuario!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                if (controllerUsuario.atualizarUsuarioController(modelUsuario)) {
                    JOptionPane.showMessageDialog(this, "Usuario Alterado com Sucesso!", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                    carregarUsuarios();
                    limparCampos();
                    habilitarDesabilitar(false);
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao Alterar o Usuario!", "ERRO", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Erro ao " + salvarAlterar + " o Usuario!\nAlgum campo VAZIO", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jTextFieldNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeUsuarioActionPerformed

    private void jTextFieldCodigoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoUsuarioActionPerformed

    private void jButtonNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoUsuarioActionPerformed
        salvarAlterar = "salvar";
        habilitarDesabilitar(true);
        limparCampos();
        jTextFieldNomeUsuario.requestFocus();
    }//GEN-LAST:event_jButtonNovoUsuarioActionPerformed

    private void jButtonAlterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarUsuarioActionPerformed
        int linha = jTableUsuario.getSelectedRow();
        /* pega o valor da linha selecionada*/

        salvarAlterar = "alterar";

        try {
            int codigoUsuario = (int) jTableUsuario.getValueAt(linha, 0);
            /* Pega o valor da coluna da linha selecionada*/

            habilitarDesabilitar(true);

            // Recupera os dados do banco
            modelUsuario = controllerUsuario.getUsuarioController(codigoUsuario);
            //Jogar na interface
            jTextFieldCodigoUsuario.setText(String.valueOf(modelUsuario.getIdUsuario()));
            jTextFieldNomeUsuario.setText(modelUsuario.getUsNome());
            jTextFieldLoginUsuario.setText(modelUsuario.getUsLogin());
            jTextFieldSenhaUsuario.setText(modelUsuario.getUsSenha());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Alterar o Cliente, Selecione um Registro na tabela", "AVISO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAlterarUsuarioActionPerformed

    private void jButtonSalvarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarUsuarioActionPerformed
        salvarAlterar();
    }//GEN-LAST:event_jButtonSalvarUsuarioActionPerformed

    private void jButtonCancelarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarUsuarioActionPerformed
        limparCampos();
        habilitarDesabilitar(false);
    }//GEN-LAST:event_jButtonCancelarUsuarioActionPerformed

    private void jButtonExcluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirUsuarioActionPerformed
        int linha = jTableUsuario.getSelectedRow();
        try {
            int codigoUsuario = (int) jTableUsuario.getValueAt(linha, 0);
            if (controllerUsuario.excluirUsuarioController(codigoUsuario)) {
                JOptionPane.showMessageDialog(this, "Usuario Excluido com Sucesso!", "Atenção", JOptionPane.WARNING_MESSAGE);
                this.carregarUsuarios();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Excluir o Usuario !", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExcluirUsuarioActionPerformed

    private void jTextFieldLoginUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoginUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoginUsuarioActionPerformed

    private void jTextFieldSenhaUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSenhaUsuarioKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) {
            salvarAlterar();
        }
    }//GEN-LAST:event_jTextFieldSenhaUsuarioKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterarUsuario;
    private javax.swing.JButton jButtonCancelarUsuario;
    private javax.swing.JButton jButtonExcluirUsuario;
    private javax.swing.JButton jButtonNovoUsuario;
    private javax.swing.JButton jButtonSalvarUsuario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuario;
    private javax.swing.JTextField jTextFieldCodigoUsuario;
    private javax.swing.JTextField jTextFieldLoginUsuario;
    private javax.swing.JFormattedTextField jTextFieldNomeUsuario;
    private javax.swing.JTextField jTextFieldSenhaUsuario;
    // End of variables declaration//GEN-END:variables
}
