/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerCliente;
import controller.ControllerProdutos;
import controller.ControllerProdutosVendasProdutos;
import controller.ControllerVendas;
import controller.ControllerVendasCliente;
import controller.ControllerVendasProdutos;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.ModelCliente;
import model.ModelProdutos;
import model.ModelProdutosVendasProdutos;
import model.ModelVendas;
import model.ModelVendasCliente;
import model.ModelVendasProdutos;
import util.BLDatas;

/**
 *
 * @author jefer
 */
public class Vendas extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ModelCliente modelCliente = new ModelCliente();
    ArrayList<ModelCliente> listaModelClientes = new ArrayList<>();
    ControllerProdutos controllerProdutos = new ControllerProdutos();
    ModelProdutos modelProdutos = new ModelProdutos();
    ArrayList<ModelProdutos> listaModelProdutos = new ArrayList<>();
    ArrayList<ModelVendasCliente> listaModelVendasClientes = new ArrayList<>();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();
    ControllerVendas controllerVendas = new ControllerVendas();
    ModelVendas modelVendas = new ModelVendas();
    BLDatas bLDatas = new BLDatas();
    ControllerVendasProdutos controllerVendasProdutos = new ControllerVendasProdutos();
    ModelVendasProdutos modelVendasProdutos = new ModelVendasProdutos();
    ArrayList<ModelVendasProdutos> listaModelVendasProdutoses = new ArrayList<>();
    ControllerProdutosVendasProdutos controllerProdutosVendasProdutos = new ControllerProdutosVendasProdutos();
    ModelProdutosVendasProdutos modelProdutosVendasProdutos = new ModelProdutosVendasProdutos();
    ArrayList<ModelProdutosVendasProdutos> listaModelProdutosVendasProdutoses = new ArrayList<>();
    int alterarSalvar = 0;

    /**
     * Creates new form Vendas
     */
    public Vendas() {
        initComponents();
        listarClientes();
        listarProdutos();
        setLocationRelativeTo(null);
        carregarVendas();
        carregarCodigoDoProduto();
        carregarCodigoDoCliente();
        carregarValorProduto();
        jTextFieldDescontoVenda.setText("0");
        jTextFieldNumeroVenda.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldCodigoClienteVenda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQuantidadeVenda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCodigoProdutoVenda = new javax.swing.JTextField();
        jTextFieldNumeroVenda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonAdicionarVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutosVenda = new javax.swing.JTable();
        jButtonNovoVenda = new javax.swing.JButton();
        jButtonCancelarVenda = new javax.swing.JButton();
        jButtonSalvarVenda = new javax.swing.JButton();
        jTextFieldDescontoVenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldTotalLiquidoVenda = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldValorDoProdutoVenda = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldValorBrutoVenda = new javax.swing.JTextField();
        jButtonRemoverProdutoVenda = new javax.swing.JButton();
        uJComboBoxNomeClienteProdutosVenda = new componentes.UJComboBox();
        uJComboBoxNomeProdutosVenda = new componentes.UJComboBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldPesquisarVendas = new javax.swing.JTextField();
        jButtonPesquisarVenda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableVendas = new javax.swing.JTable();
        jButtonExcluirVenda = new javax.swing.JButton();
        jButtonAlterarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistema de Vendas - Cadastro e Busca de Vendas");
        setResizable(false);

        jLabel1.setText("Código do Cliente:");

        jTextFieldCodigoClienteVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodigoClienteVendaFocusLost(evt);
            }
        });
        jTextFieldCodigoClienteVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoClienteVendaActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome do Cliente:");

        jLabel3.setText("Numero da Venda:");

        jLabel4.setText("Código do Produto:");

        jTextFieldCodigoProdutoVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldCodigoProdutoVendaFocusLost(evt);
            }
        });
        jTextFieldCodigoProdutoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodigoProdutoVendaActionPerformed(evt);
            }
        });

        jTextFieldNumeroVenda.setEditable(false);
        jTextFieldNumeroVenda.setBackground(new java.awt.Color(102, 255, 102));
        jTextFieldNumeroVenda.setForeground(new java.awt.Color(51, 51, 51));
        jTextFieldNumeroVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setText("Quantidade:");

        jButtonAdicionarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/carrinho-de-compras.png"))); // NOI18N
        jButtonAdicionarVenda.setText("Adicionar");
        jButtonAdicionarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarVendaActionPerformed(evt);
            }
        });

        jTableProdutosVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Produto", "Nome Produto", "Quantidade", "Valor Unitario", "Valor Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableProdutosVenda);
        if (jTableProdutosVenda.getColumnModel().getColumnCount() > 0) {
            jTableProdutosVenda.getColumnModel().getColumn(0).setMinWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(0).setPreferredWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(0).setMaxWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(2).setMinWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(2).setPreferredWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(2).setMaxWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(3).setMinWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(3).setPreferredWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(3).setMaxWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(4).setMinWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTableProdutosVenda.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        jButtonNovoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/papel-de-texto.png"))); // NOI18N
        jButtonNovoVenda.setText("Novo");
        jButtonNovoVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNovoVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonNovoVenda.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonNovoVenda.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonNovoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoVendaActionPerformed(evt);
            }
        });

        jButtonCancelarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/proibido.png"))); // NOI18N
        jButtonCancelarVenda.setText("Cancelar");
        jButtonCancelarVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonCancelarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelarVenda.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonCancelarVenda.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonCancelarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarVendaActionPerformed(evt);
            }
        });

        jButtonSalvarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/disquete.png"))); // NOI18N
        jButtonSalvarVenda.setText("Salvar");
        jButtonSalvarVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonSalvarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalvarVenda.setEnabled(false);
        jButtonSalvarVenda.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonSalvarVenda.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonSalvarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarVendaActionPerformed(evt);
            }
        });

        jTextFieldDescontoVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDescontoVendaFocusLost(evt);
            }
        });
        jTextFieldDescontoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDescontoVendaActionPerformed(evt);
            }
        });

        jLabel6.setText("Desconto (em %): ");

        jTextFieldTotalLiquidoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalLiquidoVendaActionPerformed(evt);
            }
        });

        jLabel7.setText("Valor Total:");

        jLabel9.setText("Nome do Produto:");

        jLabel10.setText("Valor:");

        jTextFieldValorDoProdutoVenda.setEditable(false);
        jTextFieldValorDoProdutoVenda.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ "))));

        jLabel11.setText("Total a Pagar:");

        jTextFieldValorBrutoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldValorBrutoVendaActionPerformed(evt);
            }
        });

        jButtonRemoverProdutoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/carrinho-de-compras-remover.png"))); // NOI18N
        jButtonRemoverProdutoVenda.setText("Remover");
        jButtonRemoverProdutoVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonRemoverProdutoVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRemoverProdutoVenda.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonRemoverProdutoVenda.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonRemoverProdutoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoverProdutoVendaActionPerformed(evt);
            }
        });

        uJComboBoxNomeClienteProdutosVenda.setAutocompletar(true);
        uJComboBoxNomeClienteProdutosVenda.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                uJComboBoxNomeClienteProdutosVendaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        uJComboBoxNomeProdutosVenda.setAutocompletar(true);
        uJComboBoxNomeProdutosVenda.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                uJComboBoxNomeProdutosVendaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonRemoverProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSalvarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDescontoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldValorBrutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldTotalLiquidoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCodigoProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uJComboBoxNomeProdutosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jTextFieldValorDoProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldQuantidadeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAdicionarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldCodigoClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3)
                                        .addGap(69, 69, 69))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(uJComboBoxNomeClienteProdutosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldNumeroVenda)))))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodigoClienteVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumeroVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uJComboBoxNomeClienteProdutosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButtonAdicionarVenda))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextFieldCodigoProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldQuantidadeVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldValorDoProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uJComboBoxNomeProdutosVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDescontoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldValorBrutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldTotalLiquidoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonCancelarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonRemoverProdutoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonSalvarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Cadastrar", jPanel1);

        jLabel8.setText("Pesquisar:");

        jButtonPesquisarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/pesquisa.png"))); // NOI18N
        jButtonPesquisarVenda.setText("Pesquisar");
        jButtonPesquisarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonPesquisarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarVendaActionPerformed(evt);
            }
        });

        jTableVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da Venda", "Nome do Cliente", "Data da Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTableVendas);
        if (jTableVendas.getColumnModel().getColumnCount() > 0) {
            jTableVendas.getColumnModel().getColumn(0).setMinWidth(110);
            jTableVendas.getColumnModel().getColumn(0).setPreferredWidth(110);
            jTableVendas.getColumnModel().getColumn(0).setMaxWidth(110);
            jTableVendas.getColumnModel().getColumn(2).setMinWidth(110);
            jTableVendas.getColumnModel().getColumn(2).setPreferredWidth(110);
            jTableVendas.getColumnModel().getColumn(2).setMaxWidth(110);
        }

        jButtonExcluirVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/cancelar.png"))); // NOI18N
        jButtonExcluirVenda.setText("Excluir");
        jButtonExcluirVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonExcluirVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExcluirVenda.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonExcluirVenda.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonExcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirVendaActionPerformed(evt);
            }
        });

        jButtonAlterarVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/24x24/editar.png"))); // NOI18N
        jButtonAlterarVenda.setText("Alterar");
        jButtonAlterarVenda.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonAlterarVenda.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAlterarVenda.setMaximumSize(new java.awt.Dimension(110, 110));
        jButtonAlterarVenda.setMinimumSize(new java.awt.Dimension(110, 110));
        jButtonAlterarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTextFieldPesquisarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addComponent(jButtonPesquisarVenda)
                        .addGap(204, 204, 204))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButtonAlterarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluirVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonPesquisarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldPesquisarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consultar/Excluir/Alterar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Lista os clientes para preencher o uJComboBoxNomeClienteProdutosVenda
    private void listarClientes() {
        listaModelClientes = controllerCliente.getListaClienteController();
        uJComboBoxNomeClienteProdutosVenda.removeAllItems();
        for (int i = 0; i < listaModelClientes.size(); i++) {
            uJComboBoxNomeClienteProdutosVenda.addItem(listaModelClientes.get(i).getCliNome());
        }
    }

    //Lista os clientes para preencher o uJComboBoxNomeProdutosVenda
    private void listarProdutos() {
        listaModelProdutos = controllerProdutos.retornarListaProdutoController();
        uJComboBoxNomeProdutosVenda.removeAllItems();
        for (int i = 0; i < listaModelProdutos.size(); i++) {
            uJComboBoxNomeProdutosVenda.addItem(listaModelProdutos.get(i).getProdNome());
        }
    }

    private void carregarVendas() {
        DefaultTableModel modelo = (DefaultTableModel) jTableVendas.getModel();
        listaModelVendasClientes = controllerVendasCliente.getListaVendasClienteController();
        modelo.setNumRows(0);//seta o numero de linhas em ZERO para nao duplicar na tabela
        //insere as vendas na tabela
        int cont = listaModelVendasClientes.size();
        for (int i = 0; i < cont; i++) {
            modelo.addRow(new Object[]{
                listaModelVendasClientes.get(i).getModelVendas().getIdVenda(),
                listaModelVendasClientes.get(i).getModelCliente().getCliNome(),
                listaModelVendasClientes.get(i).getModelVendas().getVenDataVenda()
            });
        }
    }

    private void limparVendas() {
        jTextFieldQuantidadeVenda.setText("");
        jTextFieldDescontoVenda.setText("0");
        jTextFieldValorBrutoVenda.setText("");
        jTextFieldTotalLiquidoVenda.setText("");
        jTextFieldNumeroVenda.setText("0");
        DefaultTableModel modelo = (DefaultTableModel) jTableProdutosVenda.getModel();
        modelo.setNumRows(0);
    }

    //soma o valor total dos produtos da venda
    private void somarValorToralProdutos() {
        double soma = 0, valor;
        int cont = jTableProdutosVenda.getRowCount();//conta o total de linhas da tabela

        for (int i = 0; i < cont; i++) {
            valor = (double) jTableProdutosVenda.getValueAt(i, 4);
            soma = soma + valor;
        }
        jTextFieldValorBrutoVenda.setText(String.valueOf(soma));
        aplicarDesconto();
    }

    //Calcular o desconto sobre o valor total
    private void aplicarDesconto() {
        //DecimalFormat df = new DecimalFormat("#,###.00");//formata as casas decimais de um Double
        double desconto = Double.parseDouble(jTextFieldDescontoVenda.getText());
        double valorBruto = Double.parseDouble(jTextFieldValorBrutoVenda.getText());
        double valorLiquido = valorBruto - ((desconto / 100) * valorBruto);
        //jTextFieldTotalPagarVenda.setText("R$: " + String.valueOf(df.format(totalDesconto)));
        jTextFieldTotalLiquidoVenda.setText(String.valueOf(valorLiquido));
    }

    //carregar o código do produto assim que iniciar o programa
    private void carregarCodigoDoProduto() {
        modelProdutos = controllerProdutos.retornarProdutoController(uJComboBoxNomeProdutosVenda.getSelectedItem().toString());
        jTextFieldCodigoProdutoVenda.setText(String.valueOf(modelProdutos.getIdProduto()));
    }

    //carregar o código do cliente assim que iniciar o programa
    private void carregarCodigoDoCliente() {
        modelCliente = controllerCliente.getClienteController(uJComboBoxNomeClienteProdutosVenda.getSelectedItem().toString());
        jTextFieldCodigoClienteVenda.setText(String.valueOf(modelCliente.getIdCliente()));
    }

    //Carrega o valor do produto assim que iniciar o programa ou um produto for selecionado
    private void carregarValorProduto() {
        jTextFieldValorDoProdutoVenda.setText(String.valueOf("R$: " + modelProdutos.getProdValor()));
    }

    private void jButtonPesquisarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarVendaActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) this.jTableVendas.getModel();
        final TableRowSorter<TableModel> classificador = new TableRowSorter<>(modelo);
        this.jTableVendas.setRowSorter(classificador);
        String texto = jTextFieldPesquisarVendas.getText().toUpperCase();
        classificador.setRowFilter(RowFilter.regexFilter(texto, 1));
    }//GEN-LAST:event_jButtonPesquisarVendaActionPerformed

    private void jButtonExcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirVendaActionPerformed
        //Excluir uma venda no banco
        int linha = jTableVendas.getSelectedRow();//pega a linha selecionada na tabela
        try {
            int codigoVenda = (int) jTableVendas.getValueAt(linha, 0);//pega a coluna 0 a linha selecionada
            listaModelProdutos = new ArrayList<>();
            listaModelProdutosVendasProdutoses = new ArrayList<>();
            listaModelProdutosVendasProdutoses = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);

            for (int i = 0; i < listaModelProdutosVendasProdutoses.size(); i++) {
                modelProdutos = new ModelProdutos();
                modelProdutos.setIdProduto(listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getIdProduto());
                modelProdutos.setProdEstoque(
                        listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getProdEstoque()
                        + listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProQuantidade()
                );
                listaModelProdutos.add(modelProdutos);
            }

            if (controllerProdutos.alterarEstoqueProdutoControler(listaModelProdutos)) {
                controllerVendasProdutos.excluirVendasProdutosController(codigoVenda);
                if (controllerVendas.excluirVendasController(codigoVenda)) {
                    JOptionPane.showMessageDialog(this, "Venda Excluida com SUCESSO", "ERRO", JOptionPane.WARNING_MESSAGE);
                    carregarVendas();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Excluir a Venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Excluir a Venda, Selecione um Registro na tabela", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonExcluirVendaActionPerformed

    private void jButtonAlterarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarVendaActionPerformed
        alterarSalvar = 1;
        jButtonSalvarVenda.setEnabled(true);
        System.out.println(alterarSalvar);
        try {
            int linha = jTableVendas.getSelectedRow();
            int codigoVenda = (int) jTableVendas.getValueAt(linha, 0);
            listaModelProdutosVendasProdutoses = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);
            uJComboBoxNomeClienteProdutosVenda.setSelectedItem(jTableVendas.getValueAt(linha, 1));
            carregarCodigoDoCliente();
            DefaultTableModel modelo = (DefaultTableModel) jTableProdutosVenda.getModel();
            modelo.setNumRows(0);
            for (int i = 0; i < listaModelProdutosVendasProdutoses.size(); i++) {
                jTextFieldNumeroVenda.setText(String.valueOf(listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVendas()));
                modelo.addRow(new Object[]{
                    listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getIdProduto(),
                    listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getProdNome(),
                    listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProQuantidade(),
                    listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProValor(),
                    listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProQuantidade()
                    * listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProValor()

                });
            }
            somarValorToralProdutos();
            jTabbedPane1.setSelectedIndex(0);//move entre as abas 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro ao Alterar a Venda, Selecione um Registro na tabela", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonAlterarVendaActionPerformed

    private void uJComboBoxNomeProdutosVendaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_uJComboBoxNomeProdutosVendaPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (uJComboBoxNomeProdutosVenda.isPopupVisible()) {
            modelProdutos = controllerProdutos.retornarProdutoController(uJComboBoxNomeProdutosVenda.getSelectedItem().toString());
            jTextFieldCodigoProdutoVenda.setText(String.valueOf(modelProdutos.getIdProduto()));
            carregarValorProduto();
        }
    }//GEN-LAST:event_uJComboBoxNomeProdutosVendaPopupMenuWillBecomeInvisible

    private void uJComboBoxNomeClienteProdutosVendaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_uJComboBoxNomeClienteProdutosVendaPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        if (uJComboBoxNomeClienteProdutosVenda.isPopupVisible()) {
            modelCliente = controllerCliente.getClienteController(uJComboBoxNomeClienteProdutosVenda.getSelectedItem().toString());
            jTextFieldCodigoClienteVenda.setText(String.valueOf(modelCliente.getIdCliente()));
        }
    }//GEN-LAST:event_uJComboBoxNomeClienteProdutosVendaPopupMenuWillBecomeInvisible

    private void jButtonRemoverProdutoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoverProdutoVendaActionPerformed
        int linha = jTableProdutosVenda.getSelectedRow();
        DefaultTableModel modelo = (DefaultTableModel) jTableProdutosVenda.getModel();
        modelo.removeRow(linha);
        somarValorToralProdutos();
    }//GEN-LAST:event_jButtonRemoverProdutoVendaActionPerformed

    private void jTextFieldValorBrutoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldValorBrutoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldValorBrutoVendaActionPerformed

    private void jTextFieldTotalLiquidoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalLiquidoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalLiquidoVendaActionPerformed

    private void jTextFieldDescontoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDescontoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDescontoVendaActionPerformed

    private void jTextFieldDescontoVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDescontoVendaFocusLost
        // TODO add your handling code here:
        somarValorToralProdutos();
    }//GEN-LAST:event_jTextFieldDescontoVendaFocusLost

    @SuppressWarnings("empty-statement")
    private void jButtonSalvarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarVendaActionPerformed
        int codigoVenda, codigoProduto = 0, qtdVenda = 0;
        listaModelVendasProdutoses = new ArrayList<>();
        modelVendasProdutos = new ModelVendasProdutos();
        modelProdutos = new ModelProdutos();
        /*
         IF para ver se o numero da venda nao é vazio para nao dar erro quando for alterar a venda
         pois para alterar precisa do ID da Venda
         */
        if (!jTextFieldNumeroVenda.equals("")) {
            modelVendas.setIdVenda(Integer.parseInt(jTextFieldNumeroVenda.getText()));
        }
        modelVendas.setCliente(Integer.parseInt(jTextFieldCodigoClienteVenda.getText()));
        /*
         try catch para tratar a data, pois no banco só aceita no formato americano
         */
        try {
            modelVendas.setVenDataVenda(bLDatas.converterDataParaDateUS(new java.util.Date(System.currentTimeMillis())));
        } catch (Exception e) {
            //Logger.getLogger(Vendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        modelVendas.setVenValorLiquido(Double.parseDouble(jTextFieldTotalLiquidoVenda.getText()));
        modelVendas.setVenValorBruto(Double.parseDouble(jTextFieldValorBrutoVenda.getText()));
        modelVendas.setVenDesconto(Double.parseDouble(jTextFieldDescontoVenda.getText()));

        /*
         Aqui é onde entro no metodo de salvar ou alterar
         */
        if (alterarSalvar == 0) {
            //SALVAR UMA NOVA VENDA NO BANCO
            codigoVenda = controllerVendas.salvarVendasController(modelVendas);
            if (codigoVenda > 0) {
                JOptionPane.showMessageDialog(this, "Venda Concluida com SUCESSO", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Concluir a Venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            }

            int cont = jTableProdutosVenda.getRowCount();//pega quantas linhas tem na tabela
            for (int i = 0; i < cont; i++) {
                codigoProduto = (int) jTableProdutosVenda.getValueAt(i, 0);
                qtdVenda = Integer.parseInt(jTableProdutosVenda.getValueAt(i, 2).toString());
                modelVendasProdutos = new ModelVendasProdutos();
                modelProdutos = new ModelProdutos();
                modelVendasProdutos.setProduto(codigoProduto);
                modelVendasProdutos.setVendas(codigoVenda);
                modelVendasProdutos.setVenProValor((double) jTableProdutosVenda.getValueAt(i, 3));
                modelVendasProdutos.setVenProQuantidade(qtdVenda);
                listaModelVendasProdutoses.add(modelVendasProdutos);
                //subtrai a quantidade vendida no estoque
                modelProdutos.setIdProduto(codigoProduto);
                modelProdutos.setProdEstoque(controllerProdutos.retornarProdutoController(codigoProduto).getProdEstoque()
                        - qtdVenda);
                listaModelProdutos.add(modelProdutos);
            }

            //salvar os produtos da venda
            if (controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutoses)) {
                //JOptionPane.showMessageDialog(this, "Venda Concluida com SUCESSO", "SUCESSO", JOptionPane.INFORMATION_MESSAGE);
                controllerProdutos.alterarEstoqueProdutoControler(listaModelProdutos);//Alterar o estoque no banco
                limparVendas();
                carregarVendas();
            } else {
                //JOptionPane.showMessageDialog(this, "Erro ao Concluir a Venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            };

        } //ALTERAR UMA VENDA JA CONCLUIDA
        else if (alterarSalvar == 1) {
            try {
                modelVendasProdutos = new ModelVendasProdutos();
                //INICIO -> retornar os produtos para o estoque e excluir os produtos da venda
                codigoVenda = Integer.parseInt(jTextFieldNumeroVenda.getText());
                listaModelProdutos = new ArrayList<>();
                listaModelProdutosVendasProdutoses = new ArrayList<>();
                listaModelProdutosVendasProdutoses = controllerProdutosVendasProdutos.getListaProdutosVendasProdutosController(codigoVenda);

                for (int i = 0; i < listaModelProdutosVendasProdutoses.size(); i++) {
                    modelProdutos = new ModelProdutos();
                    modelProdutos.setIdProduto(listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getIdProduto());
                    modelProdutos.setProdEstoque(
                            listaModelProdutosVendasProdutoses.get(i).getModelProdutos().getProdEstoque()
                            + listaModelProdutosVendasProdutoses.get(i).getModelVendasProdutos().getVenProQuantidade()
                    );
                    listaModelProdutos.add(modelProdutos);
                }

                if (controllerProdutos.alterarEstoqueProdutoControler(listaModelProdutos)) {
                    controllerVendasProdutos.excluirVendasProdutosController(codigoVenda);
                    carregarVendas();
                }
                //FIM -> retornar os produtos para o estoque e excluir os produtos da venda

                controllerVendas.atualizarVendasController(modelVendas);

                int cont = jTableProdutosVenda.getRowCount();//pega quantas linhas tem na tabela
                for (int i = 0; i < cont; i++) {
                    codigoProduto = (int) jTableProdutosVenda.getValueAt(i, 0);
                    qtdVenda = Integer.parseInt(jTableProdutosVenda.getValueAt(i, 2).toString());
                    modelVendasProdutos = new ModelVendasProdutos();
                    modelProdutos = new ModelProdutos();
                    modelVendasProdutos.setProduto(codigoProduto);
                    modelVendasProdutos.setVendas(codigoVenda);
                    modelVendasProdutos.setVenProValor((double) jTableProdutosVenda.getValueAt(i, 3));
                    modelVendasProdutos.setVenProQuantidade(qtdVenda);
                    //subtrai a quantidade vendida no estoque
                    modelProdutos.setIdProduto(codigoProduto);
                    modelProdutos.setProdEstoque(controllerProdutos.retornarProdutoController(codigoProduto).getProdEstoque()
                            - qtdVenda);
                    listaModelVendasProdutoses.add(modelVendasProdutos);
                    listaModelProdutos.add(modelProdutos);
                }
                //Salvar os produtos da alteração da venda
                controllerVendasProdutos.salvarVendasProdutosController(listaModelVendasProdutoses);//Salva as vendas na tb_vendas_produtos
                controllerProdutos.alterarEstoqueProdutoControler(listaModelProdutos);// atualiza o estoque na tb_produto
                carregarVendas();
                limparVendas();
                JOptionPane.showMessageDialog(this, "Venda Alterada com SUCESSO", "ERRO", JOptionPane.WARNING_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao Alterar a Venda", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }
        jButtonSalvarVenda.setEnabled(true);
    }//GEN-LAST:event_jButtonSalvarVendaActionPerformed

    private void jButtonCancelarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarVendaActionPerformed

    }//GEN-LAST:event_jButtonCancelarVendaActionPerformed

    private void jButtonNovoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoVendaActionPerformed
        alterarSalvar = 0;
        jButtonSalvarVenda.setEnabled(true);
        limparVendas();
    }//GEN-LAST:event_jButtonNovoVendaActionPerformed

    private void jButtonAdicionarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarVendaActionPerformed
        if (jTextFieldQuantidadeVenda.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "ERRO ao adicionar a Venda, QUANTIDADE vazio!", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        } else {
            modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(jTextFieldCodigoProdutoVenda.getText()));
            //adiciona uma linha na tabela
            DefaultTableModel modelo = (DefaultTableModel) jTableProdutosVenda.getModel();
            int cont = 0;
            double qtde = Double.parseDouble(jTextFieldQuantidadeVenda.getText());
            for (int i = 0; i < cont; i++) {
                modelo.setNumRows(0);
            }

            modelo.addRow(new Object[]{
                modelProdutos.getIdProduto(),
                modelProdutos.getProdNome(),
                jTextFieldQuantidadeVenda.getText(),
                modelProdutos.getProdValor(),
                qtde * modelProdutos.getProdValor(),});
            somarValorToralProdutos();
        }
    }//GEN-LAST:event_jButtonAdicionarVendaActionPerformed

    private void jTextFieldCodigoProdutoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProdutoVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoProdutoVendaActionPerformed

    private void jTextFieldCodigoProdutoVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodigoProdutoVendaFocusLost
        // TODO add your handling code here:.
        modelProdutos = controllerProdutos.retornarProdutoController(Integer.parseInt(jTextFieldCodigoProdutoVenda.getText()));
        uJComboBoxNomeProdutosVenda.setSelectedItem(modelProdutos.getProdNome());
    }//GEN-LAST:event_jTextFieldCodigoProdutoVendaFocusLost

    private void jTextFieldCodigoClienteVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodigoClienteVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodigoClienteVendaActionPerformed

    private void jTextFieldCodigoClienteVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldCodigoClienteVendaFocusLost
        // TODO add your handling code here:
        modelCliente = controllerCliente.getClienteController(Integer.parseInt(jTextFieldCodigoClienteVenda.getText()));
        uJComboBoxNomeClienteProdutosVenda.setSelectedItem(modelCliente.getCliNome());
    }//GEN-LAST:event_jTextFieldCodigoClienteVendaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdicionarVenda;
    private javax.swing.JButton jButtonAlterarVenda;
    private javax.swing.JButton jButtonCancelarVenda;
    private javax.swing.JButton jButtonExcluirVenda;
    private javax.swing.JButton jButtonNovoVenda;
    private javax.swing.JButton jButtonPesquisarVenda;
    private javax.swing.JButton jButtonRemoverProdutoVenda;
    private javax.swing.JButton jButtonSalvarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableProdutosVenda;
    private javax.swing.JTable jTableVendas;
    private javax.swing.JTextField jTextFieldCodigoClienteVenda;
    private javax.swing.JTextField jTextFieldCodigoProdutoVenda;
    private javax.swing.JTextField jTextFieldDescontoVenda;
    private javax.swing.JTextField jTextFieldNumeroVenda;
    private javax.swing.JTextField jTextFieldPesquisarVendas;
    private javax.swing.JTextField jTextFieldQuantidadeVenda;
    private javax.swing.JTextField jTextFieldTotalLiquidoVenda;
    private javax.swing.JTextField jTextFieldValorBrutoVenda;
    private javax.swing.JFormattedTextField jTextFieldValorDoProdutoVenda;
    private componentes.UJComboBox uJComboBoxNomeClienteProdutosVenda;
    private componentes.UJComboBox uJComboBoxNomeProdutosVenda;
    // End of variables declaration//GEN-END:variables
}
